# Analysis of Android App Build Reproducibility

This notebook analyzes the reproducibility of Android app builds across different environments and build methods.

In [9]:
import hashlib
import io
import itertools
import json
import os
import pathlib
import shutil
import sys
from collections import defaultdict
from pathlib import Path

import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

## Methodology

To test the reproducibility of the Android application, we have followed [the guide in the official repository](https://github.com/signalapp/Signal-Android/tree/main/reproducible-builds). Initially, we have run each step manually, and then wrote [a custom script](https://github.com/TheTechZone/reproducible-tests/blob/main/build_signal.py) to automate the process and prevent errors that could be introduced by humans.
Each build output was obtained using a clean<a name="clean"></a>[<sup>[clean]</sup>](#clean) Docker container. 

All tests very carried again version `v7.25.2` of the Signal application, which the most recent version currently available on Play Store (`region=CH`, `releaseChannel=production`). [According to public info](https://github.com/signalapp/Signal-Android/issues/13754#issuecomment-2450435519), this version should include the recent proguard fixes that ensure build determinism (TODO: link the commits)

The only variability in environment consists of the host operating system that was used (`fedora-40`, `fedora-41`, and `ubuntu-24.04`). Each machine was connected to a diffrent physical Android device for retrieving the play store app.

Example of footnote.


<a name="clean"></a> [^clean](#clean) Before invoking Gradle, the Docker image was built from scratch with no caching to prevent build artifacts from affecting reproducibility.  -- see the `./clean` script
[^clean]: )

## Data Collection

First, let's collect information about all the builds in our outputs directory.

In [10]:
def get_file_hash(filepath):
    """Calculate SHA-256 hash of a file."""
    sha256_hash = hashlib.sha256()
    with open(filepath, "rb") as f:
        for byte_block in iter(lambda: f.read(4096), b""):
            sha256_hash.update(byte_block)
    return sha256_hash.hexdigest()


def collect_build_data(output_dir):
    """Collect build data from the outputs directory."""
    builds_data = []

    def human_size(bytes, units=[" bytes", "KB", "MB", "GB", "TB", "PB", "EB"]):
        """Returns a human readable string representation of bytes"""
        return (
            str(bytes) + units[0]
            if bytes < 1024
            else human_size(bytes >> 10, units[1:])
        )

    for build_dir in Path(output_dir).iterdir():
        if not build_dir.is_dir():
            continue

        if "checkpoints" in build_dir.name:
            continue

        # Parse environment info from directory name
        env_info = build_dir.name.split("-")
        os_name = env_info[0]
        build_type = env_info[1]
        execution_count = 1 if len(env_info) == 2 else int(env_info[2])

        # Process APKs
        for apk_dir in build_dir.glob("**/apks*"):
            apk_type = apk_dir.name
            for apk_file in apk_dir.glob("**/*.apk"):
                size = apk_file.stat().st_size
                builds_data.append(
                    {
                        "os": os_name,
                        "build_type": build_type,
                        "exec_count": execution_count,
                        "apk_type": apk_type,
                        "local_apk": apk_type == "apks-i-built",
                        "filename": apk_file.name,
                        "filepath": str(apk_file),
                        "hash": get_file_hash(apk_file),
                        "size": size,
                        "human_size": human_size(size),
                    }
                )

    return pd.DataFrame(builds_data)


# Collect data
output_dir = "data/runs"
df = collect_build_data(output_dir)
df.head(50)

,os,build_type,exec_count,apk_type,local_apk,filename,filepath,hash,size,human_size
0,fedora40_dfs_sort_reverse,scripted,1,apks-i-built,True,base-arm64_v8a.apk,data/runs/fedora40_dfs_sort_reverse-scripted/a...,995c37061435d46d5f3d7caf4fe7e1817a8b9a0d4049a7...,10699335,10MB
1,fedora40_dfs_sort_reverse,scripted,1,apks-i-built,True,base-master.apk,data/runs/fedora40_dfs_sort_reverse-scripted/a...,243e0a3b54cd8b21046155f7fccbe08def0a998f8ecdf0...,52381043,49MB
2,fedora40_dfs_sort_reverse,scripted,1,apks-i-built,True,base-xxhdpi.apk,data/runs/fedora40_dfs_sort_reverse-scripted/a...,41b12629671ba0778364d671909add3a94380955c5c366...,1637689,1MB
3,fedora40_dfs_sort,scripted,1,apks-i-built,True,base-arm64_v8a.apk,data/runs/fedora40_dfs_sort-scripted/apks-i-bu...,995c37061435d46d5f3d7caf4fe7e1817a8b9a0d4049a7...,10699335,10MB
4,fedora40_dfs_sort,scripted,1,apks-i-built,True,base-master.apk,data/runs/fedora40_dfs_sort-scripted/apks-i-bu...,ed0c8b3e94ba72dc96920b55732c29dd8038c6446df5b0...,52380815,49MB
5,fedora40_dfs_sort,scripted,1,apks-i-built,True,base-xxhdpi.apk,data/runs/fedora40_dfs_sort-scripted/apks-i-bu...,41b12629671ba0778364d671909add3a94380955c5c366...,1637689,1MB
6,fedora40,manual,1,apks-from-device,False,base-arm64_v8a.apk,data/runs/fedora40-manual/apks-from-device/bas...,d296fff8691b3632f85725202045875af7e89dafedc9df...,23569519,22MB
7,fedora40,manual,1,apks-from-device,False,base-master.apk,data/runs/fedora40-manual/apks-from-device/bas...,eb1902b3aa98e15a140e9de574dfa47b78bf8bb85fc556...,85037580,81MB
8,fedora40,manual,1,apks-from-device,False,base-xxhdpi.apk,data/runs/fedora40-manual/apks-from-device/bas...,c65a2691cde28650f8934d492bff6c241b2e55eee4d222...,1666719,1MB
9,fedora40,manual,1,apks-i-built,True,base-arm64_v8a.apk,data/runs/fedora40-manual/apks-i-built/base-ar...,a74d526fd13f4fe3bda7e066c575fa0c931d8da7333b8d...,23561264,22MB
10,fedora40,manual,1,apks-i-built,True,base-master.apk,data/runs/fedora40-manual/apks-i-built/base-ma...,4768602685c6e5ceff078093c87e9aba5f19597b0d76c5...,85021050,81MB
11,fedora40,manual,1,apks-i-built,True,base-xxhdpi.apk,data/runs/fedora40-manual/apks-i-built/base-xx...,51119b048c0e03525cbb253ed7c19974738b58804908d3...,1658464,1MB
12,fedora40,scripted,1,apks-from-device,False,base-arm64_v8a.apk,data/runs/fedora40-scripted-1/apks-from-device...,d296fff8691b3632f85725202045875af7e89dafedc9df...,23569519,22MB
13,fedora40,scripted,1,apks-from-device,False,base-master.apk,data/runs/fedora40-scripted-1/apks-from-device...,eb1902b3aa98e15a140e9de574dfa47b78bf8bb85fc556...,85037580,81MB
14,fedora40,scripted,1,apks-from-device,False,base-xxhdpi.apk,data/runs/fedora40-scripted-1/apks-from-device...,c65a2691cde28650f8934d492bff6c241b2e55eee4d222...,1666719,1MB
15,fedora40,scripted,1,apks-i-built,True,base-arm64_v8a.apk,data/runs/fedora40-scripted-1/apks-i-built/bas...,a74d526fd13f4fe3bda7e066c575fa0c931d8da7333b8d...,23561264,22MB
16,fedora40,scripted,1,apks-i-built,True,base-master.apk,data/runs/fedora40-scripted-1/apks-i-built/bas...,4768602685c6e5ceff078093c87e9aba5f19597b0d76c5...,85021050,81MB
17,fedora40,scripted,1,apks-i-built,True,base-xxhdpi.apk,data/runs/fedora40-scripted-1/apks-i-built/bas...,51119b048c0e03525cbb253ed7c19974738b58804908d3...,1658464,1MB
18,fedora40,scripted,2,apks-from-device,False,base-arm64_v8a.apk,data/runs/fedora40-scripted-2/apks-from-device...,d296fff8691b3632f85725202045875af7e89dafedc9df...,23569519,22MB
19,fedora40,scripted,2,apks-from-device,False,base-master.apk,data/runs/fedora40-scripted-2/apks-from-device...,eb1902b3aa98e15a140e9de574dfa47b78bf8bb85fc556...,85037580,81MB
20,fedora40,scripted,2,apks-from-device,False,base-xxhdpi.apk,data/runs/fedora40-scripted-2/apks-from-device...,c65a2691cde28650f8934d492bff6c241b2e55eee4d222...,1666719,1MB
21,fedora40,scripted,2,apks-i-built,True,base-arm64_v8a.apk,data/runs/fedora40-scripted-2/apks-i-built/bas...,a74d526fd13f4fe3bda7e066c575fa0c931d8da7333b8d...,23561264,22MB
22,fedora40,scripted,2,apks-i-built,True,base-master.apk,data/runs/fedora40-scripted-2/apks-i-built/bas...,4768602685c6e5ceff078093c87e9aba5f19597b0d76c5...,85021050,81MB
23,fedora40,scripted,2,apks-i-built,True,base-xxhdpi.apk,data/runs/fedora40-scripted-2/apks-i-built/bas...,51119b048c0e03525cbb253ed7c19974738b58804908d3...,1658464,1MB
24,fedora41_dfs_sort_reverse,scripted,1,apks-i-built,True,base-arm64_v8a.apk,data/runs/fedora41_dfs_sort_reverse-scripted/a...,995c37061435d46d5f3d7caf4fe7e1817a8b9a0d4049a7...,10699335,10MB
25,fedora41_dfs_sort_reverse,scripted,1,apks-i-built,True,base-master.apk,data/runs/fedora41_dfs_sort_reverse-scripted/a...,ed0c8b3e94ba72dc96920b55732c29dd8038c6446df5b0...,52380815,49MB
26,fedora41_dfs_sort_reverse,scripted,1,apks-i-built,True,base-xxhdpi.apk,data/runs/fedora41_dfs_sort_reverse-scripted/a...,41b12629671ba0778364d671909add3a94380955c5c366...,1637689,1MB
27,fedora41_dfs_sort,scripted,1,apks-i-built,True,base-arm64_v8a.apk,data/runs/fedora41_dfs_sort-scripted/apks-i-bu...,995c37061435d46d5f3d7caf4fe7e1817a8b9a0d4049a7...,10699335,10MB
28,fedora41_dfs_sort,scripted,1,apks-i-built,True,base-master.apk,data/runs/fedora41_dfs_sort-scripted/apks-i-bu...,243e0a3b54cd8b21046155f7fccbe08def0a998f8ecdf0...,52381043,49MB
29,fedora41_dfs_sort,scripted,1,apks-i-built,True,base-xxhdpi.apk,data/runs/fedora41_dfs_sort-scripted/apks-i-bu...,41b12629671ba0778364d671909add3a94380955c5c366...,1637689,1MB
30,fedora41,scripted,1,apks-from-device,False,base-arm64_v8a.apk,data/runs/fedora41-scripted-1/apks-from-device...,d296fff8691b3632f85725202045875af7e89dafedc9df...,23569519,22MB
31,fedora41,scripted,1,apks-from-device,False,base-master.apk,data/runs/fedora41-scripted-1/apks-from-device...,eb1902b3aa98e15a140e9de574dfa47b78bf8bb85fc556...,85037580,81MB
32,fedora41,scripted,1,apks-from-device,False,base-xxhdpi.apk,data/runs/fedora41-scripted-1/apks-from-device...,c65a2691cde28650f8934d492bff6c241b2e55eee4d222...,1666719,1MB
33,fedora41,scripted,1,apks-i-built,True,base-arm64_v8a.apk,data/runs/fedora41-scripted-1/apks-i-built/bas...,4832f3a837a4059db7476c45d995045b0c561388234335...,23552089,22MB
34,fedora41,scripted,1,apks-i-built,True,base-master.apk,data/runs/fedora41-scripted-1/apks-i-built/bas...,dbe76a3649f90f061170c6d3d2071bcddc3c32672bebc2...,84693087,80MB
35,fedora41,scripted,1,apks-i-built,True,base-xxhdpi.apk,data/runs/fedora41-scripted-1/apks-i-built/bas...,41b12629671ba0778364d671909add3a94380955c5c366...,1637689,1MB
36,ubuntu22_dfs_sort_reverse,scripted,1,apks-i-built,True,base-arm64_v8a.apk,data/runs/ubuntu22_dfs_sort_reverse-scripted/a...,995c37061435d46d5f3d7caf4fe7e1817a8b9a0d4049a7...,10699335,10MB
37,ubuntu22_dfs_sort_reverse,scripted,1,apks-i-built,True,base-master.apk,data/runs/ubuntu22_dfs_sort_reverse-scripted/a...,11b479c5082ca4323ab811d05288283f079f881f665619...,52381531,49MB
38,ubuntu22_dfs_sort_reverse,scripted,1,apks-i-built,True,base-xxhdpi.apk,data/runs/ubuntu22_dfs_sort_reverse-scripted/a...,41b12629671ba0778364d671909add3a94380955c5c366...,1637689,1MB
39,ubuntu22_dfs_sort,scripted,1,apks-i-built,True,base-arm64_v8a.apk,data/runs/ubuntu22_dfs_sort-scripted/apks-i-bu...,995c37061435d46d5f3d7caf4fe7e1817a8b9a0d4049a7...,10699335,10MB
40,ubuntu22_dfs_sort,scripted,1,apks-i-built,True,base-master.apk,data/runs/ubuntu22_dfs_sort-scripted/apks-i-bu...,391c7b876ff6aa67b5922f3699c17f3beb21ff0913ba6a...,52381303,49MB
41,ubuntu22_dfs_sort,scripted,1,apks-i-built,True,base-xxhdpi.apk,data/runs/ubuntu22_dfs_sort-scripted/apks-i-bu...,41b12629671ba0778364d671909add3a94380955c5c366...,1637689,1MB
42,ubuntu22,scripted,1,apks-from-device,False,base-arm64_v8a.apk,data/runs/ubuntu22-scripted-1/apks-from-device...,d296fff8691b3632f85725202045875af7e89dafedc9df...,23569519,22MB
43,ubuntu22,scripted,1,apks-from-device,False,base-master.apk,data/runs/ubuntu22-scripted-1/apks-from-device...,eb1902b3aa98e15a140e9de574dfa47b78bf8bb85fc556...,85037580,81MB
44,ubuntu22,scripted,1,apks-from-device,False,base-xxhdpi.apk,data/runs/ubuntu22-scripted-1/apks-from-device...,c65a2691cde28650f8934d492bff6c241b2e55eee4d222...,1666719,1MB
45,ubuntu22,scripted,1,apks-i-built,True,base-arm64_v8a.apk,data/runs/ubuntu22-scripted-1/apks-i-built/bas...,4832f3a837a4059db7476c45d995045b0c561388234335...,23552089,22MB
46,ubuntu22,scripted,1,apks-i-built,True,base-master.apk,data/runs/ubuntu22-scripted-1/apks-i-built/bas...,fa1e7eec6dc3e634aae9ccba817d04db46b46c10ca4556...,84693087,80MB
47,ubuntu22,scripted,1,apks-i-built,True,base-xxhdpi.apk,data/runs/ubuntu22-scripted-1/apks-i-built/bas...,41b12629671ba0778364d671909add3a94380955c5c366...,1637689,1MB

In [11]:
def print_tree_with_hashes(df):
    """Print directory tree with file hashes."""
    # Create a nested dictionary structure
    tree = defaultdict(lambda: defaultdict(lambda: defaultdict(dict)))

    # ANSI color codes
    BLUE = "\033[34m"
    PURPLE = "\33[35m"
    BOLD = "\033[1m"
    RESET = "\033[0m"

    # Populate the tree structure
    for _, row in df.iterrows():
        tree[row["os"]][row["build_type"]][row["apk_type"]][row["filename"]] = row[
            "hash"
        ][
            :8
        ]  # First 8 chars of hash

    # Print the tree
    for os in sorted(tree.keys()):
        print(f"{BLUE}{BOLD}{os}/{RESET}")
        for build_type in sorted(tree[os].keys()):
            print(f"├── {BLUE}{BOLD}{build_type}/{RESET}")
            for apk_type in sorted(tree[os][build_type].keys()):
                print(f"│   ├── {BLUE}{BOLD}{apk_type}/{RESET}")
                for filename, hash_prefix in sorted(
                    tree[os][build_type][apk_type].items()
                ):
                    print(
                        f"│   │   ├── {filename} [hash: {PURPLE}{BOLD}{hash_prefix}{RESET}]"
                    )
    print("..... Done")


print("Directory Tree with Hash Prefixes (first 8 chars):")
print_tree_with_hashes(df)

Directory Tree with Hash Prefixes (first 8 chars):
fedora40/
├── manual/
│   ├── apks-from-device/
│   │   ├── base-arm64_v8a.apk [hash: d296fff8]
│   │   ├── base-master.apk [hash: eb1902b3]
│   │   ├── base-xxhdpi.apk [hash: c65a2691]
│   ├── apks-i-built/
│   │   ├── base-arm64_v8a.apk [hash: a74d526f]
│   │   ├── base-master.apk [hash: 47686026]
│   │   ├── base-xxhdpi.apk [hash: 51119b04]
├── scripted/
│   ├── apks-from-device/
│   │   ├── base-arm64_v8a.apk [hash: d296fff8]
│   │   ├── base-master.apk [hash: eb1902b3]
│   │   ├── base-xxhdpi.apk [hash: c65a2691]
│   ├── apks-i-built/
│   │   ├── base-arm64_v8a.apk [hash: a74d526f]
│   │   ├── base-master.apk [hash: 47686026]
│   │   ├── base-xxhdpi.apk [hash: 51119b04]
fedora40_dfs_sort/
├── scripted/
│   ├── apks-i-built/
│   │   ├── base-arm64_v8a.apk [hash: 995c3706]
│   │   ├── base-master.apk [hash: ed0c8b3e]
│   │   ├── base-xxhdpi.apk [hash: 41b12629]
fedora40_dfs_sort_reverse/
├── scripted/
│   ├── apks-i-built/
│   │   ├── base-arm64_v8a.apk [hash: 995c3706]
│   │   ├── base-master.apk [hash: 243e0a3b]
│   │   ├── base-xxhdpi.apk [hash: 41b12629]
fedora41/
├── scripted/
│   ├── apks-from-device/
│   │   ├── base-arm64_v8a.apk [hash: d296fff8]
│   │   ├── base-master.apk [hash: eb1902b3]
│   │   ├── base-xxhdpi.apk [hash: c65a2691]
│   ├── apks-i-built/
│   │   ├── base-arm64_v8a.apk [hash: 4832f3a8]
│   │   ├── base-master.apk [hash: dbe76a36]
│   │   ├── base-xxhdpi.apk [hash: 41b12629]
fedora41_dfs_sort/
├── scripted/
│   ├── apks-i-built/
│   │   ├── base-arm64_v8a.apk [hash: 995c3706]
│   │   ├── base-master.apk [hash: 243e0a3b]
│   │   ├── base-xxhdpi.apk [hash: 41b12629]
fedora41_dfs_sort_reverse/
├── scripted/
│   ├── apks-i-built/
│   │   ├── base-arm64_v8a.apk [hash: 995c3706]
│   │   ├── base-master.apk [hash: ed0c8b3e]
│   │   ├── base-xxhdpi.apk [hash: 41b12629]
ubuntu22/
├── scripted/
│   ├── apks-from-device/
│   │   ├── base-arm64_v8a.apk [hash: d296fff8]
│   │   ├── base-master.apk [hash: eb1902b3]
│   │   ├── base-xxhdpi.apk [hash: c65a2691]
│   ├── apks-i-built/
│   │   ├── base-arm64_v8a.apk [hash: 4832f3a8]
│   │   ├── base-master.apk [hash: fa1e7eec]
│   │   ├── base-xxhdpi.apk [hash: 41b12629]
ubuntu22_dfs_sort/
├── scripted/
│   ├── apks-i-built/
│   │   ├── base-arm64_v8a.apk [hash: 995c3706]
│   │   ├── base-master.apk [hash: 391c7b87]
│   │   ├── base-xxhdpi.apk [hash: 41b12629]
ubuntu22_dfs_sort_reverse/
├── scripted/
│   ├── apks-i-built/
│   │   ├── base-arm64_v8a.apk [hash: 995c3706]
│   │   ├── base-master.apk [hash: 11b479c5]
│   │   ├── base-xxhdpi.apk [hash: 41b12629]
..... Done

## Build Reproducibility Analysis

Let's analyze the reproducibility of builds by comparing hashes across different environments.

In [12]:
df.groupby(["os", "build_type"])["exec_count"].nunique().reset_index(
    name="execution_times"
).rename_axis(None).set_index(["os", "build_type"])

                                      execution_times
os                        build_type
fedora40                  manual                    1
                          scripted                  2
fedora40_dfs_sort         scripted                  1
fedora40_dfs_sort_reverse scripted                  1
fedora41                  scripted                  1
fedora41_dfs_sort         scripted                  1
fedora41_dfs_sort_reverse scripted                  1
ubuntu22                  scripted                  1
ubuntu22_dfs_sort         scripted                  1
ubuntu22_dfs_sort_reverse scripted                  1

> So indeed, 5 total runs, 4 of them scripted as explained in Methodology

In [13]:
df[~df["local_apk"]].groupby("filename")["hash"].nunique().reset_index(
    name="distinct file hashes"
).set_index("filename")

                    distinct file hashes
filename
base-arm64_v8a.apk                     1
base-master.apk                        1
base-xxhdpi.apk                        1

> So, we have only one unique variant of each apk file, which implies that every phone received the same apk bundle (splits) when

Sanity check: do all the builds in the same environment produce the same apk?

In [14]:
df[df["local_apk"]].groupby(["os", "filename"])["hash"].nunique().reset_index(
    name="distinct file hashes"
).set_index(["os", "filename"])

                                              distinct file hashes
os                        filename
fedora40                  base-arm64_v8a.apk                     1
                          base-master.apk                        1
                          base-xxhdpi.apk                        1
fedora40_dfs_sort         base-arm64_v8a.apk                     1
                          base-master.apk                        1
                          base-xxhdpi.apk                        1
fedora40_dfs_sort_reverse base-arm64_v8a.apk                     1
                          base-master.apk                        1
                          base-xxhdpi.apk                        1
fedora41                  base-arm64_v8a.apk                     1
                          base-master.apk                        1
                          base-xxhdpi.apk                        1
fedora41_dfs_sort         base-arm64_v8a.apk                     1
                          base-master.apk                        1
                          base-xxhdpi.apk                        1
fedora41_dfs_sort_reverse base-arm64_v8a.apk                     1
                          base-master.apk                        1
                          base-xxhdpi.apk                        1
ubuntu22                  base-arm64_v8a.apk                     1
                          base-master.apk                        1
                          base-xxhdpi.apk                        1
ubuntu22_dfs_sort         base-arm64_v8a.apk                     1
                          base-master.apk                        1
                          base-xxhdpi.apk                        1
ubuntu22_dfs_sort_reverse base-arm64_v8a.apk                     1
                          base-master.apk                        1
                          base-xxhdpi.apk                        1

> So, the host operating system does NOT introduce variability with regards to the built of subsequent apk (bunndles)

In [15]:
df[df["local_apk"]].groupby(["filename"])["hash"].nunique()

filename
base-arm64_v8a.apk    3
base-master.apk       7
base-xxhdpi.apk       2
Name: hash, dtype: int64

In [16]:
# Step 1: Group by 'filename' and count unique 'hash' values
unique_hashes_count = df[df["local_apk"]].groupby("filename")["hash"].nunique()

# Step 2: Filter filenames where the unique hash count is greater than 1
diverging_filenames = unique_hashes_count[unique_hashes_count > 1].index

# Step 3: Extract rows where the 'filename' is in the list of filenames with multiple unique hashes
divergent_data = df[df["local_apk"] & df["filename"].isin(diverging_filenames)]

# Step 4: Group by 'filename' and get the relevant columns
result = (
    divergent_data.groupby(["filename", "hash"])[["os", "filepath"]]
    .agg(
        {
            "os": "first",  # Pick the first 'os' for each filename (assuming it's consistent within each group)
            "filepath": "first",  # Pick the first 'filepath' for each filename (assuming it's consistent within each group)
            # 'hash': 'unique'       # Get all unique hash values for each filename
        }
    )
    .reset_index()
)

# Step 5: Show only rows where there are multiple hashes (you can remove this step if needed)
result = result[result["hash"].apply(len) > 1]

# Show the result
result.set_index(["filename", "os"])

                                                                                           hash  \
filename           os
base-arm64_v8a.apk fedora41                   4832f3a837a4059db7476c45d995045b0c561388234335...
                   fedora40_dfs_sort_reverse  995c37061435d46d5f3d7caf4fe7e1817a8b9a0d4049a7...
                   fedora40                   a74d526fd13f4fe3bda7e066c575fa0c931d8da7333b8d...
base-master.apk    ubuntu22_dfs_sort_reverse  11b479c5082ca4323ab811d05288283f079f881f665619...
                   fedora40_dfs_sort_reverse  243e0a3b54cd8b21046155f7fccbe08def0a998f8ecdf0...
                   ubuntu22_dfs_sort          391c7b876ff6aa67b5922f3699c17f3beb21ff0913ba6a...
                   fedora40                   4768602685c6e5ceff078093c87e9aba5f19597b0d76c5...
                   fedora41                   dbe76a3649f90f061170c6d3d2071bcddc3c32672bebc2...
                   fedora40_dfs_sort          ed0c8b3e94ba72dc96920b55732c29dd8038c6446df5b0...
                   ubuntu22                   fa1e7eec6dc3e634aae9ccba817d04db46b46c10ca4556...
base-xxhdpi.apk    fedora40_dfs_sort_reverse  41b12629671ba0778364d671909add3a94380955c5c366...
                   fedora40                   51119b048c0e03525cbb253ed7c19974738b58804908d3...

                                                                                       filepath
filename           os
base-arm64_v8a.apk fedora41                   data/runs/fedora41-scripted-1/apks-i-built/bas...
                   fedora40_dfs_sort_reverse  data/runs/fedora40_dfs_sort_reverse-scripted/a...
                   fedora40                   data/runs/fedora40-manual/apks-i-built/base-ar...
base-master.apk    ubuntu22_dfs_sort_reverse  data/runs/ubuntu22_dfs_sort_reverse-scripted/a...
                   fedora40_dfs_sort_reverse  data/runs/fedora40_dfs_sort_reverse-scripted/a...
                   ubuntu22_dfs_sort          data/runs/ubuntu22_dfs_sort-scripted/apks-i-bu...
                   fedora40                   data/runs/fedora40-manual/apks-i-built/base-ma...
                   fedora41                   data/runs/fedora41-scripted-1/apks-i-built/bas...
                   fedora40_dfs_sort          data/runs/fedora40_dfs_sort-scripted/apks-i-bu...
                   ubuntu22                   data/runs/ubuntu22-scripted-1/apks-i-built/bas...
base-xxhdpi.apk    fedora40_dfs_sort_reverse  data/runs/fedora40_dfs_sort_reverse-scripted/a...
                   fedora40                   data/runs/fedora40-manual/apks-i-built/base-xx...

> What about ubuntu22?

In [17]:
frame = df[(df["os"] == "ubuntu22") & (df["local_apk"])][
    ["os", "filename", "filepath", "hash"]
]
frame2 = df[(df["os"] == "ubuntu22_dfs_sort") & (df["local_apk"])][
    ["os", "filename", "filepath", "hash"]
]
frame3 = df[(df["os"] == "ubuntu22_dfs_sort_reverse") & (df["local_apk"])][
    ["os", "filename", "filepath", "hash"]
]
frame = pd.concat([frame, frame2, frame3])
frame

,os,filename,filepath,hash
45,ubuntu22,base-arm64_v8a.apk,data/runs/ubuntu22-scripted-1/apks-i-built/bas...,4832f3a837a4059db7476c45d995045b0c561388234335...
46,ubuntu22,base-master.apk,data/runs/ubuntu22-scripted-1/apks-i-built/bas...,fa1e7eec6dc3e634aae9ccba817d04db46b46c10ca4556...
47,ubuntu22,base-xxhdpi.apk,data/runs/ubuntu22-scripted-1/apks-i-built/bas...,41b12629671ba0778364d671909add3a94380955c5c366...
39,ubuntu22_dfs_sort,base-arm64_v8a.apk,data/runs/ubuntu22_dfs_sort-scripted/apks-i-bu...,995c37061435d46d5f3d7caf4fe7e1817a8b9a0d4049a7...
40,ubuntu22_dfs_sort,base-master.apk,data/runs/ubuntu22_dfs_sort-scripted/apks-i-bu...,391c7b876ff6aa67b5922f3699c17f3beb21ff0913ba6a...
41,ubuntu22_dfs_sort,base-xxhdpi.apk,data/runs/ubuntu22_dfs_sort-scripted/apks-i-bu...,41b12629671ba0778364d671909add3a94380955c5c366...
36,ubuntu22_dfs_sort_reverse,base-arm64_v8a.apk,data/runs/ubuntu22_dfs_sort_reverse-scripted/a...,995c37061435d46d5f3d7caf4fe7e1817a8b9a0d4049a7...
37,ubuntu22_dfs_sort_reverse,base-master.apk,data/runs/ubuntu22_dfs_sort_reverse-scripted/a...,11b479c5082ca4323ab811d05288283f079f881f665619...
38,ubuntu22_dfs_sort_reverse,base-xxhdpi.apk,data/runs/ubuntu22_dfs_sort_reverse-scripted/a...,41b12629671ba0778364d671909add3a94380955c5c366...

> So, it produced a similar `base-arm64_v8a.apk` and `base-xxhdpi.apk` as fedora41, but different than fedora40. Each os has a unique `base-master.apk`

## Investigation

In [18]:
from build_signal import SignalBuilder
import argparse

args = argparse.Namespace()
args.version = "v7.25.2"
args.clean = None
args.dfs = None
args.purge = None
args.debug = None
args.aab_only = None
sb = SignalBuilder(args)

##
sb.disorderfs_root_dir = (
    sb.disorderfs_root_dir / "../"
).resolve()  # hotfix for disorderfs update
sb.signal_repo_dir = sb.disorderfs_root_dir / "Signal-Android"

In [19]:
# sb.clone_signal("7.25.2")
# !mkdir -p reproducible-signal

In [20]:
from pathlib import Path

sb.setup_apkdiff(Path("./"))

Setting up apkdiff.py...

PosixPath('/home/adrian/Dev/GIT_lfs/reproducible-tests/reproducible-signal/apkdiff.py')

In [21]:
from apkdiff import ApkDiff

In [22]:
df.columns

Index(['os', 'build_type', 'exec_count', 'apk_type', 'local_apk', 'filename',
       'filepath', 'hash', 'size', 'human_size'],
      dtype='object')

In [23]:
# Group by 'filename' and drop duplicate entries by 'hash'
df_unique = df.groupby("filename").apply(
    lambda group: group.drop_duplicates(subset=["hash"])
)

# Reset the index to get a clean DataFrame
df_unique = df_unique.reset_index(drop=True)

# Display the result
df_unique.set_index(["filename", "os"])

/tmp/ipykernel_60254/465915602.py:2: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df_unique = df.groupby("filename").apply(

                                             build_type  exec_count  \
filename           os
base-arm64_v8a.apk fedora40_dfs_sort_reverse   scripted           1
                   fedora40                      manual           1
                   fedora40                      manual           1
                   fedora41                    scripted           1
base-master.apk    fedora40_dfs_sort_reverse   scripted           1
                   fedora40_dfs_sort           scripted           1
                   fedora40                      manual           1
                   fedora40                      manual           1
                   fedora41                    scripted           1
                   ubuntu22_dfs_sort_reverse   scripted           1
                   ubuntu22_dfs_sort           scripted           1
                   ubuntu22                    scripted           1
base-xxhdpi.apk    fedora40_dfs_sort_reverse   scripted           1
                   fedora40                      manual           1
                   fedora40                      manual           1

                                                      apk_type  local_apk  \
filename           os
base-arm64_v8a.apk fedora40_dfs_sort_reverse      apks-i-built       True
                   fedora40                   apks-from-device      False
                   fedora40                       apks-i-built       True
                   fedora41                       apks-i-built       True
base-master.apk    fedora40_dfs_sort_reverse      apks-i-built       True
                   fedora40_dfs_sort              apks-i-built       True
                   fedora40                   apks-from-device      False
                   fedora40                       apks-i-built       True
                   fedora41                       apks-i-built       True
                   ubuntu22_dfs_sort_reverse      apks-i-built       True
                   ubuntu22_dfs_sort              apks-i-built       True
                   ubuntu22                       apks-i-built       True
base-xxhdpi.apk    fedora40_dfs_sort_reverse      apks-i-built       True
                   fedora40                   apks-from-device      False
                   fedora40                       apks-i-built       True

                                                                                       filepath  \
filename           os
base-arm64_v8a.apk fedora40_dfs_sort_reverse  data/runs/fedora40_dfs_sort_reverse-scripted/a...
                   fedora40                   data/runs/fedora40-manual/apks-from-device/bas...
                   fedora40                   data/runs/fedora40-manual/apks-i-built/base-ar...
                   fedora41                   data/runs/fedora41-scripted-1/apks-i-built/bas...
base-master.apk    fedora40_dfs_sort_reverse  data/runs/fedora40_dfs_sort_reverse-scripted/a...
                   fedora40_dfs_sort          data/runs/fedora40_dfs_sort-scripted/apks-i-bu...
                   fedora40                   data/runs/fedora40-manual/apks-from-device/bas...
                   fedora40                   data/runs/fedora40-manual/apks-i-built/base-ma...
                   fedora41                   data/runs/fedora41-scripted-1/apks-i-built/bas...
                   ubuntu22_dfs_sort_reverse  data/runs/ubuntu22_dfs_sort_reverse-scripted/a...
                   ubuntu22_dfs_sort          data/runs/ubuntu22_dfs_sort-scripted/apks-i-bu...
                   ubuntu22                   data/runs/ubuntu22-scripted-1/apks-i-built/bas...
base-xxhdpi.apk    fedora40_dfs_sort_reverse  data/runs/fedora40_dfs_sort_reverse-scripted/a...
                   fedora40                   data/runs/fedora40-manual/apks-from-device/bas...
                   fedora40                   data/runs/fedora40-manual/apks-i-built/base-xx...

                                                                                           hash  \
filename           os
base-arm64_v8a.apk fedora40_dfs_sort_reverse  995c37061435d46d5f3d7caf4fe7e1817a8b9a0d4049a7...
                   fedora40                   d296fff8691b3632f85725202045875af7e89dafedc9df...
                   fedora40                   a74d526fd13f4fe3bda7e066c575fa0c931d8da7333b8d...
                   fedora41                   4832f3a837a4059db7476c45d995045b0c561388234335...
base-master.apk    fedora40_dfs_sort_reverse  243e0a3b54cd8b21046155f7fccbe08def0a998f8ecdf0...
                   fedora40_dfs_sort          ed0c8b3e94ba72dc96920b55732c29dd8038c6446df5b0...
                   fedora40                   eb1902b3aa98e15a140e9de574dfa47b78bf8bb85fc556...
                   fedora40                   4768602685c6e5ceff078093c87e9aba5f19597b0d76c5...
                   fedora41                   dbe76a3649f90f061170c6d3d2071bcddc3c32672bebc2...
                   ubuntu22_dfs_sort_reverse  11b479c5082ca4323ab811d05288283f079f881f665619...
                   ubuntu22_dfs_sort          391c7b876ff6aa67b5922f3699c17f3beb21ff0913ba6a...
                   ubuntu22                   fa1e7eec6dc3e634aae9ccba817d04db46b46c10ca4556...
base-xxhdpi.apk    fedora40_dfs_sort_reverse  41b12629671ba0778364d671909add3a94380955c5c366...
                   fedora40                   c65a2691cde28650f8934d492bff6c241b2e55eee4d222...
                   fedora40                   51119b048c0e03525cbb253ed7c19974738b58804908d3...

                                                  size human_size
filename           os
base-arm64_v8a.apk fedora40_dfs_sort_reverse  10699335       10MB
                   fedora40                   23569519       22MB
                   fedora40                   23561264       22MB
                   fedora41                   23552089       22MB
base-master.apk    fedora40_dfs_sort_reverse  52381043       49MB
                   fedora40_dfs_sort          52380815       49MB
                   fedora40                   85037580       81MB
                   fedora40                   85021050       81MB
                   fedora41                   84693087       80MB
                   ubuntu22_dfs_sort_reverse  52381531       49MB
                   ubuntu22_dfs_sort          52381303       49MB
                   ubuntu22                   84693087       80MB
base-xxhdpi.apk    fedora40_dfs_sort_reverse   1637689        1MB
                   fedora40                    1666719        1MB
                   fedora40                    1658464        1MB

In [24]:
# Step 1: Group by the 'filename' index level
grouped = df_unique.groupby("filename")

# Step 2: For each group, generate all pairs of rows (without repetition)
pairs = []
for filename, group in grouped:
    # If the group has more than one row, create combinations of indices
    if len(group) > 1:
        # Generate all unique combinations of row indices for this group
        for index1, index2 in itertools.combinations(group.index, 2):
            pair_data = {
                "filename": filename,
                "pair": (index1, index2),
                "row_1_data": group.loc[index1].to_dict(),
                "row_2_data": group.loc[index2].to_dict(),
            }
            pairs.append(pair_data)

# Step 3: Convert the list of pairs into a DataFrame
pairs_df = pd.DataFrame(pairs)

# Show the pairs DataFrame
pairs_df

,filename,pair,row_1_data,row_2_data
0,base-arm64_v8a.apk,"(0, 1)","{'os': 'fedora40_dfs_sort_reverse', 'build_typ...","{'os': 'fedora40', 'build_type': 'manual', 'ex..."
1,base-arm64_v8a.apk,"(0, 2)","{'os': 'fedora40_dfs_sort_reverse', 'build_typ...","{'os': 'fedora40', 'build_type': 'manual', 'ex..."
2,base-arm64_v8a.apk,"(0, 3)","{'os': 'fedora40_dfs_sort_reverse', 'build_typ...","{'os': 'fedora41', 'build_type': 'scripted', '..."
3,base-arm64_v8a.apk,"(1, 2)","{'os': 'fedora40', 'build_type': 'manual', 'ex...","{'os': 'fedora40', 'build_type': 'manual', 'ex..."
4,base-arm64_v8a.apk,"(1, 3)","{'os': 'fedora40', 'build_type': 'manual', 'ex...","{'os': 'fedora41', 'build_type': 'scripted', '..."
5,base-arm64_v8a.apk,"(2, 3)","{'os': 'fedora40', 'build_type': 'manual', 'ex...","{'os': 'fedora41', 'build_type': 'scripted', '..."
6,base-master.apk,"(4, 5)","{'os': 'fedora40_dfs_sort_reverse', 'build_typ...","{'os': 'fedora40_dfs_sort', 'build_type': 'scr..."
7,base-master.apk,"(4, 6)","{'os': 'fedora40_dfs_sort_reverse', 'build_typ...","{'os': 'fedora40', 'build_type': 'manual', 'ex..."
8,base-master.apk,"(4, 7)","{'os': 'fedora40_dfs_sort_reverse', 'build_typ...","{'os': 'fedora40', 'build_type': 'manual', 'ex..."
9,base-master.apk,"(4, 8)","{'os': 'fedora40_dfs_sort_reverse', 'build_typ...","{'os': 'fedora41', 'build_type': 'scripted', '..."
10,base-master.apk,"(4, 9)","{'os': 'fedora40_dfs_sort_reverse', 'build_typ...","{'os': 'ubuntu22_dfs_sort_reverse', 'build_typ..."
11,base-master.apk,"(4, 10)","{'os': 'fedora40_dfs_sort_reverse', 'build_typ...","{'os': 'ubuntu22_dfs_sort', 'build_type': 'scr..."
12,base-master.apk,"(4, 11)","{'os': 'fedora40_dfs_sort_reverse', 'build_typ...","{'os': 'ubuntu22', 'build_type': 'scripted', '..."
13,base-master.apk,"(5, 6)","{'os': 'fedora40_dfs_sort', 'build_type': 'scr...","{'os': 'fedora40', 'build_type': 'manual', 'ex..."
14,base-master.apk,"(5, 7)","{'os': 'fedora40_dfs_sort', 'build_type': 'scr...","{'os': 'fedora40', 'build_type': 'manual', 'ex..."
15,base-master.apk,"(5, 8)","{'os': 'fedora40_dfs_sort', 'build_type': 'scr...","{'os': 'fedora41', 'build_type': 'scripted', '..."
16,base-master.apk,"(5, 9)","{'os': 'fedora40_dfs_sort', 'build_type': 'scr...","{'os': 'ubuntu22_dfs_sort_reverse', 'build_typ..."
17,base-master.apk,"(5, 10)","{'os': 'fedora40_dfs_sort', 'build_type': 'scr...","{'os': 'ubuntu22_dfs_sort', 'build_type': 'scr..."
18,base-master.apk,"(5, 11)","{'os': 'fedora40_dfs_sort', 'build_type': 'scr...","{'os': 'ubuntu22', 'build_type': 'scripted', '..."
19,base-master.apk,"(6, 7)","{'os': 'fedora40', 'build_type': 'manual', 'ex...","{'os': 'fedora40', 'build_type': 'manual', 'ex..."
20,base-master.apk,"(6, 8)","{'os': 'fedora40', 'build_type': 'manual', 'ex...","{'os': 'fedora41', 'build_type': 'scripted', '..."
21,base-master.apk,"(6, 9)","{'os': 'fedora40', 'build_type': 'manual', 'ex...","{'os': 'ubuntu22_dfs_sort_reverse', 'build_typ..."
22,base-master.apk,"(6, 10)","{'os': 'fedora40', 'build_type': 'manual', 'ex...","{'os': 'ubuntu22_dfs_sort', 'build_type': 'scr..."
23,base-master.apk,"(6, 11)","{'os': 'fedora40', 'build_type': 'manual', 'ex...","{'os': 'ubuntu22', 'build_type': 'scripted', '..."
24,base-master.apk,"(7, 8)","{'os': 'fedora40', 'build_type': 'manual', 'ex...","{'os': 'fedora41', 'build_type': 'scripted', '..."
25,base-master.apk,"(7, 9)","{'os': 'fedora40', 'build_type': 'manual', 'ex...","{'os': 'ubuntu22_dfs_sort_reverse', 'build_typ..."
26,base-master.apk,"(7, 10)","{'os': 'fedora40', 'build_type': 'manual', 'ex...","{'os': 'ubuntu22_dfs_sort', 'build_type': 'scr..."
27,base-master.apk,"(7, 11)","{'os': 'fedora40', 'build_type': 'manual', 'ex...","{'os': 'ubuntu22', 'build_type': 'scripted', '..."
28,base-master.apk,"(8, 9)","{'os': 'fedora41', 'build_type': 'scripted', '...","{'os': 'ubuntu22_dfs_sort_reverse', 'build_typ..."
29,base-master.apk,"(8, 10)","{'os': 'fedora41', 'build_type': 'scripted', '...","{'os': 'ubuntu22_dfs_sort', 'build_type': 'scr..."
30,base-master.apk,"(8, 11)","{'os': 'fedora41', 'build_type': 'scripted', '...","{'os': 'ubuntu22', 'build_type': 'scripted', '..."
31,base-master.apk,"(9, 10)","{'os': 'ubuntu22_dfs_sort_reverse', 'build_typ...","{'os': 'ubuntu22_dfs_sort', 'build_type': 'scr..."
32,base-master.apk,"(9, 11)","{'os': 'ubuntu22_dfs_sort_reverse', 'build_typ...","{'os': 'ubuntu22', 'build_type': 'scripted', '..."
33,base-master.apk,"(10, 11)","{'os': 'ubuntu22_dfs_sort', 'build_type': 'scr...","{'os': 'ubuntu22', 'build_type': 'scripted', '..."
34,base-xxhdpi.apk,"(12, 13)","{'os': 'fedora40_dfs_sort_reverse', 'build_typ...","{'os': 'fedora40', 'build_type': 'manual', 'ex..."
35,base-xxhdpi.apk,"(12, 14)","{'os': 'fedora40_dfs_sort_reverse', 'build_typ...","{'os': 'fedora40', 'build_type': 'manual', 'ex..."
36,base-xxhdpi.apk,"(13, 14)","{'os': 'fedora40', 'build_type': 'manual', 'ex...","{'os': 'fedora40', 'build_type': 'manual', 'ex..."

In [25]:
pairs_df["row_1_data"][0]

{'os': 'fedora40_dfs_sort_reverse',
 'build_type': 'scripted',
 'exec_count': 1,
 'apk_type': 'apks-i-built',
 'local_apk': True,
 'filename': 'base-arm64_v8a.apk',
 'filepath': 'data/runs/fedora40_dfs_sort_reverse-scripted/apks-i-built/base-arm64_v8a.apk',
 'hash': '995c37061435d46d5f3d7caf4fe7e1817a8b9a0d4049a723c99dcd8e04d5e0e2',
 'size': 10699335,
 'human_size': '10MB'}

In [28]:
# ApkDiff.compare()
for index, test in pairs_df.iterrows():
    r1, r2 = test["row_1_data"], test["row_2_data"]
    print(r1)
    print(r2)
    # ApkDiff().compare(r1['filepath'], r2['filepath'])

    break

{'os': 'fedora40_dfs_sort_reverse', 'build_type': 'scripted', 'exec_count': 1, 'apk_type': 'apks-i-built', 'local_apk': True, 'filename': 'base-arm64_v8a.apk', 'filepath': 'data/runs/fedora40_dfs_sort_reverse-scripted/apks-i-built/base-arm64_v8a.apk', 'hash': '995c37061435d46d5f3d7caf4fe7e1817a8b9a0d4049a723c99dcd8e04d5e0e2', 'size': 10699335, 'human_size': '10MB'}
{'os': 'fedora40', 'build_type': 'manual', 'exec_count': 1, 'apk_type': 'apks-from-device', 'local_apk': False, 'filename': 'base-arm64_v8a.apk', 'filepath': 'data/runs/fedora40-manual/apks-from-device/base-arm64_v8a.apk', 'hash': 'd296fff8691b3632f85725202045875af7e89dafedc9df17a455120bff6f1791', 'size': 23569519, 'human_size': '22MB'}

In [29]:
import io
import re
from contextlib import redirect_stdout

In [30]:
apkdiff_result_path = pathlib.Path("intermediates/apkdiff-results")
mismatch_folder = pathlib.Path(f"mismatches")

if apkdiff_result_path.exists() and apkdiff_result_path.is_dir():
    shutil.rmtree(apkdiff_result_path)
apkdiff_result_path.mkdir(parents=True, exist_ok=True)
if mismatch_folder.exists() and mismatch_folder.is_dir():
    shutil.rmtree(mismatch_folder)


def extract_filename(output: str):
    # Regular expression to extract filenames
    pattern = r"APKs differ on file ([\w/.-]+)!"
    return re.findall(pattern, output)


for index, row in pairs_df.iterrows():
    r1, r2 = row["row_1_data"], row["row_2_data"]
    l1 = r1["os"] if r1["local_apk"] else "playstore"
    l2 = r2["os"] if r2["local_apk"] else "playstore"
    test_idx_folder = apkdiff_result_path / f"{r1['filename']}_{l1}_vs_{l2}"

    print(f"Test #{index+1}: comparing {r1['filename']} -- {l1} with {l2}")

    output, res = None, False
    with io.StringIO() as buf, redirect_stdout(buf):
        res = ApkDiff().compare(r1["filepath"], r2["filepath"])
        output = buf.getvalue()

    if res:
        print("	APKS match [OK] ^^")
    else:
        diffs = extract_filename(output)
        print(diffs)

        # Step 3: Generate the mismatch folder (simulated command execution)
        diff1_folder = mismatch_folder / "first"
        diff2_folder = mismatch_folder / "second"

        test_idx_folder.mkdir(parents=True, exist_ok=True)
        shutil.move(str(diff1_folder), str(test_idx_folder / "first"))
        shutil.move(str(diff2_folder), str(test_idx_folder / "second"))

    print(f"Output results in {test_idx_folder}" "")
    # break
    print("=====================")

if mismatch_folder.exists() and mismatch_folder.is_dir():
    shutil.rmtree(mismatch_folder)

Test #1: comparing base-arm64_v8a.apk -- fedora40_dfs_sort_reverse with playstore
['AndroidManifest.xml']
Output results in intermediates/apkdiff-results/base-arm64_v8a.apk_fedora40_dfs_sort_reverse_vs_playstore
=====================
Test #2: comparing base-arm64_v8a.apk -- fedora40_dfs_sort_reverse with fedora40
	APKS match [OK] ^^
Output results in intermediates/apkdiff-results/base-arm64_v8a.apk_fedora40_dfs_sort_reverse_vs_fedora40
=====================
Test #3: comparing base-arm64_v8a.apk -- fedora40_dfs_sort_reverse with fedora41
	APKS match [OK] ^^
Output results in intermediates/apkdiff-results/base-arm64_v8a.apk_fedora40_dfs_sort_reverse_vs_fedora41
=====================
Test #4: comparing base-arm64_v8a.apk -- playstore with fedora40
['AndroidManifest.xml']
Output results in intermediates/apkdiff-results/base-arm64_v8a.apk_playstore_vs_fedora40
=====================
Test #5: comparing base-arm64_v8a.apk -- playstore with fedora41
['AndroidManifest.xml']
Output results in intermediates/apkdiff-results/base-arm64_v8a.apk_playstore_vs_fedora41
=====================
Test #6: comparing base-arm64_v8a.apk -- fedora40 with fedora41
	APKS match [OK] ^^
Output results in intermediates/apkdiff-results/base-arm64_v8a.apk_fedora40_vs_fedora41
=====================
Test #7: comparing base-master.apk -- fedora40_dfs_sort_reverse with fedora40_dfs_sort
['assets/dexopt/baseline.prof', 'assets/dexopt/baseline.profm', 'classes.dex', 'classes2.dex', 'classes3.dex', 'classes4.dex', 'classes5.dex', 'classes6.dex']
Output results in intermediates/apkdiff-results/base-master.apk_fedora40_dfs_sort_reverse_vs_fedora40_dfs_sort
=====================
Test #8: comparing base-master.apk -- fedora40_dfs_sort_reverse with playstore
['AndroidManifest.xml', 'assets/dexopt/baseline.prof', 'assets/dexopt/baseline.profm', 'classes.dex', 'classes2.dex', 'classes3.dex', 'classes4.dex', 'classes5.dex', 'classes6.dex', 'res/xml/splits0.xml', 'resources.arsc']
Output results in intermediates/apkdiff-results/base-master.apk_fedora40_dfs_sort_reverse_vs_playstore
=====================
Test #9: comparing base-master.apk -- fedora40_dfs_sort_reverse with fedora40
['AndroidManifest.xml', 'assets/dexopt/baseline.prof', 'assets/dexopt/baseline.profm', 'classes.dex', 'classes2.dex', 'classes3.dex', 'classes4.dex', 'classes5.dex', 'classes6.dex']
Output results in intermediates/apkdiff-results/base-master.apk_fedora40_dfs_sort_reverse_vs_fedora40
=====================
Test #10: comparing base-master.apk -- fedora40_dfs_sort_reverse with fedora41
['AndroidManifest.xml', 'assets/dexopt/baseline.prof', 'assets/dexopt/baseline.profm', 'classes.dex', 'classes2.dex', 'classes3.dex', 'classes4.dex', 'classes5.dex', 'classes6.dex']
Output results in intermediates/apkdiff-results/base-master.apk_fedora40_dfs_sort_reverse_vs_fedora41
=====================
Test #11: comparing base-master.apk -- fedora40_dfs_sort_reverse with ubuntu22_dfs_sort_reverse
['CDSI.proto', 'DecryptedGroups.proto', 'Groups.proto', 'Provisioning.proto', 'RegistrationProvisioning.proto', 'SVR2.proto', 'SignalService.proto', 'StorageService.proto', 'res/raw/map_style.json', 'res/raw/third_party_licenses']
Output results in intermediates/apkdiff-results/base-master.apk_fedora40_dfs_sort_reverse_vs_ubuntu22_dfs_sort_reverse
=====================
Test #12: comparing base-master.apk -- fedora40_dfs_sort_reverse with ubuntu22_dfs_sort
['CDSI.proto', 'DecryptedGroups.proto', 'Groups.proto', 'Provisioning.proto', 'RegistrationProvisioning.proto', 'SVR2.proto', 'SignalService.proto', 'StorageService.proto', 'assets/dexopt/baseline.prof', 'assets/dexopt/baseline.profm', 'classes.dex', 'classes2.dex', 'classes3.dex', 'classes4.dex', 'classes5.dex', 'classes6.dex', 'res/raw/map_style.json', 'res/raw/third_party_licenses']
Output results in intermediates/apkdiff-results/base-master.apk_fedora40_dfs_sort_reverse_vs_ubuntu22_dfs_sort
=====================
Test #13: comparing base-master.apk -- fedora40_dfs_sort_reverse with ubuntu22
['AndroidManifest.xml', 'assets/dexopt/baseline.prof', 'assets/dexopt/baseline.profm', 'classes.dex', 'classes2.dex', 'classes3.dex', 'classes4.dex', 'classes5.dex', 'classes6.dex']
Output results in intermediates/apkdiff-results/base-master.apk_fedora40_dfs_sort_reverse_vs_ubuntu22
=====================
Test #14: comparing base-master.apk -- fedora40_dfs_sort with playstore
['AndroidManifest.xml', 'classes2.dex', 'classes3.dex', 'classes4.dex', 'classes6.dex', 'res/xml/splits0.xml', 'resources.arsc']
Output results in intermediates/apkdiff-results/base-master.apk_fedora40_dfs_sort_vs_playstore
=====================
Test #15: comparing base-master.apk -- fedora40_dfs_sort with fedora40
['AndroidManifest.xml', 'classes2.dex', 'classes3.dex', 'classes4.dex', 'classes5.dex', 'classes6.dex']
Output results in intermediates/apkdiff-results/base-master.apk_fedora40_dfs_sort_vs_fedora40
=====================
Test #16: comparing base-master.apk -- fedora40_dfs_sort with fedora41
['AndroidManifest.xml', 'classes2.dex', 'classes3.dex', 'classes4.dex', 'classes5.dex', 'classes6.dex']
Output results in intermediates/apkdiff-results/base-master.apk_fedora40_dfs_sort_vs_fedora41
=====================
Test #17: comparing base-master.apk -- fedora40_dfs_sort with ubuntu22_dfs_sort_reverse
['CDSI.proto', 'DecryptedGroups.proto', 'Groups.proto', 'Provisioning.proto', 'RegistrationProvisioning.proto', 'SVR2.proto', 'SignalService.proto', 'StorageService.proto', 'assets/dexopt/baseline.prof', 'assets/dexopt/baseline.profm', 'classes.dex', 'classes2.dex', 'classes3.dex', 'classes4.dex', 'classes5.dex', 'classes6.dex', 'res/raw/map_style.json', 'res/raw/third_party_licenses']
Output results in intermediates/apkdiff-results/base-master.apk_fedora40_dfs_sort_vs_ubuntu22_dfs_sort_reverse
=====================
Test #18: comparing base-master.apk -- fedora40_dfs_sort with ubuntu22_dfs_sort
['CDSI.proto', 'DecryptedGroups.proto', 'Groups.proto', 'Provisioning.proto', 'RegistrationProvisioning.proto', 'SVR2.proto', 'SignalService.proto', 'StorageService.proto', 'res/raw/map_style.json', 'res/raw/third_party_licenses']
Output results in intermediates/apkdiff-results/base-master.apk_fedora40_dfs_sort_vs_ubuntu22_dfs_sort
=====================
Test #19: comparing base-master.apk -- fedora40_dfs_sort with ubuntu22
['AndroidManifest.xml', 'classes2.dex', 'classes3.dex', 'classes4.dex', 'classes5.dex', 'classes6.dex']
Output results in intermediates/apkdiff-results/base-master.apk_fedora40_dfs_sort_vs_ubuntu22
=====================
Test #20: comparing base-master.apk -- playstore with fedora40
['AndroidManifest.xml', 'classes2.dex', 'classes3.dex', 'classes4.dex', 'classes5.dex', 'classes6.dex', 'res/xml/splits0.xml', 'resources.arsc']
Output results in intermediates/apkdiff-results/base-master.apk_playstore_vs_fedora40
=====================
Test #21: comparing base-master.apk -- playstore with fedora41
['AndroidManifest.xml', 'classes2.dex', 'classes3.dex', 'classes4.dex', 'classes5.dex', 'classes6.dex', 'res/xml/splits0.xml', 'resources.arsc']
Output results in intermediates/apkdiff-results/base-master.apk_playstore_vs_fedora41
=====================
Test #22: comparing base-master.apk -- playstore with ubuntu22_dfs_sort_reverse
['AndroidManifest.xml', 'CDSI.proto', 'DecryptedGroups.proto', 'Groups.proto', 'Provisioning.proto', 'RegistrationProvisioning.proto', 'SVR2.proto', 'SignalService.proto', 'StorageService.proto', 'assets/dexopt/baseline.prof', 'assets/dexopt/baseline.profm', 'classes.dex', 'classes2.dex', 'classes3.dex', 'classes4.dex', 'classes5.dex', 'classes6.dex', 'res/raw/map_style.json', 'res/raw/third_party_licenses', 'res/xml/splits0.xml', 'resources.arsc']
Output results in intermediates/apkdiff-results/base-master.apk_playstore_vs_ubuntu22_dfs_sort_reverse
=====================
Test #23: comparing base-master.apk -- playstore with ubuntu22_dfs_sort
['AndroidManifest.xml', 'CDSI.proto', 'DecryptedGroups.proto', 'Groups.proto', 'Provisioning.proto', 'RegistrationProvisioning.proto', 'SVR2.proto', 'SignalService.proto', 'StorageService.proto', 'classes2.dex', 'classes3.dex', 'classes4.dex', 'classes6.dex', 'res/raw/map_style.json', 'res/raw/third_party_licenses', 'res/xml/splits0.xml', 'resources.arsc']
Output results in intermediates/apkdiff-results/base-master.apk_playstore_vs_ubuntu22_dfs_sort
=====================
Test #24: comparing base-master.apk -- playstore with ubuntu22
['AndroidManifest.xml', 'classes3.dex', 'classes4.dex', 'classes5.dex', 'classes6.dex', 'res/xml/splits0.xml', 'resources.arsc']
Output results in intermediates/apkdiff-results/base-master.apk_playstore_vs_ubuntu22
=====================
Test #25: comparing base-master.apk -- fedora40 with fedora41
	APKS match [OK] ^^
Output results in intermediates/apkdiff-results/base-master.apk_fedora40_vs_fedora41
=====================
Test #26: comparing base-master.apk -- fedora40 with ubuntu22_dfs_sort_reverse
['AndroidManifest.xml', 'CDSI.proto', 'DecryptedGroups.proto', 'Groups.proto', 'Provisioning.proto', 'RegistrationProvisioning.proto', 'SVR2.proto', 'SignalService.proto', 'StorageService.proto', 'assets/dexopt/baseline.prof', 'assets/dexopt/baseline.profm', 'classes.dex', 'classes2.dex', 'classes3.dex', 'classes4.dex', 'classes5.dex', 'classes6.dex', 'res/raw/map_style.json', 'res/raw/third_party_licenses']
Output results in intermediates/apkdiff-results/base-master.apk_fedora40_vs_ubuntu22_dfs_sort_reverse
=====================
Test #27: comparing base-master.apk -- fedora40 with ubuntu22_dfs_sort
['AndroidManifest.xml', 'CDSI.proto', 'DecryptedGroups.proto', 'Groups.proto', 'Provisioning.proto', 'RegistrationProvisioning.proto', 'SVR2.proto', 'SignalService.proto', 'StorageService.proto', 'classes2.dex', 'classes3.dex', 'classes4.dex', 'classes5.dex', 'classes6.dex', 'res/raw/map_style.json', 'res/raw/third_party_licenses']
Output results in intermediates/apkdiff-results/base-master.apk_fedora40_vs_ubuntu22_dfs_sort
=====================
Test #28: comparing base-master.apk -- fedora40 with ubuntu22
['classes2.dex', 'classes3.dex', 'classes4.dex', 'classes6.dex']
Output results in intermediates/apkdiff-results/base-master.apk_fedora40_vs_ubuntu22
=====================
Test #29: comparing base-master.apk -- fedora41 with ubuntu22_dfs_sort_reverse
['AndroidManifest.xml', 'CDSI.proto', 'DecryptedGroups.proto', 'Groups.proto', 'Provisioning.proto', 'RegistrationProvisioning.proto', 'SVR2.proto', 'SignalService.proto', 'StorageService.proto', 'assets/dexopt/baseline.prof', 'assets/dexopt/baseline.profm', 'classes.dex', 'classes2.dex', 'classes3.dex', 'classes4.dex', 'classes5.dex', 'classes6.dex', 'res/raw/map_style.json', 'res/raw/third_party_licenses']
Output results in intermediates/apkdiff-results/base-master.apk_fedora41_vs_ubuntu22_dfs_sort_reverse
=====================
Test #30: comparing base-master.apk -- fedora41 with ubuntu22_dfs_sort
['AndroidManifest.xml', 'CDSI.proto', 'DecryptedGroups.proto', 'Groups.proto', 'Provisioning.proto', 'RegistrationProvisioning.proto', 'SVR2.proto', 'SignalService.proto', 'StorageService.proto', 'classes2.dex', 'classes3.dex', 'classes4.dex', 'classes5.dex', 'classes6.dex', 'res/raw/map_style.json', 'res/raw/third_party_licenses']
Output results in intermediates/apkdiff-results/base-master.apk_fedora41_vs_ubuntu22_dfs_sort
=====================
Test #31: comparing base-master.apk -- fedora41 with ubuntu22
['classes2.dex', 'classes3.dex', 'classes4.dex', 'classes6.dex']
Output results in intermediates/apkdiff-results/base-master.apk_fedora41_vs_ubuntu22
=====================
Test #32: comparing base-master.apk -- ubuntu22_dfs_sort_reverse with ubuntu22_dfs_sort
['assets/dexopt/baseline.prof', 'assets/dexopt/baseline.profm', 'classes.dex', 'classes2.dex', 'classes3.dex', 'classes4.dex', 'classes5.dex', 'classes6.dex']
Output results in intermediates/apkdiff-results/base-master.apk_ubuntu22_dfs_sort_reverse_vs_ubuntu22_dfs_sort
=====================
Test #33: comparing base-master.apk -- ubuntu22_dfs_sort_reverse with ubuntu22
['AndroidManifest.xml', 'CDSI.proto', 'DecryptedGroups.proto', 'Groups.proto', 'Provisioning.proto', 'RegistrationProvisioning.proto', 'SVR2.proto', 'SignalService.proto', 'StorageService.proto', 'assets/dexopt/baseline.prof', 'assets/dexopt/baseline.profm', 'classes.dex', 'classes2.dex', 'classes3.dex', 'classes4.dex', 'classes5.dex', 'classes6.dex', 'res/raw/map_style.json', 'res/raw/third_party_licenses']
Output results in intermediates/apkdiff-results/base-master.apk_ubuntu22_dfs_sort_reverse_vs_ubuntu22
=====================
Test #34: comparing base-master.apk -- ubuntu22_dfs_sort with ubuntu22
['AndroidManifest.xml', 'CDSI.proto', 'DecryptedGroups.proto', 'Groups.proto', 'Provisioning.proto', 'RegistrationProvisioning.proto', 'SVR2.proto', 'SignalService.proto', 'StorageService.proto', 'classes2.dex', 'classes3.dex', 'classes4.dex', 'classes5.dex', 'classes6.dex', 'res/raw/map_style.json', 'res/raw/third_party_licenses']
Output results in intermediates/apkdiff-results/base-master.apk_ubuntu22_dfs_sort_vs_ubuntu22
=====================
Test #35: comparing base-xxhdpi.apk -- fedora40_dfs_sort_reverse with playstore
['AndroidManifest.xml', 'resources.arsc']
Output results in intermediates/apkdiff-results/base-xxhdpi.apk_fedora40_dfs_sort_reverse_vs_playstore
=====================
Test #36: comparing base-xxhdpi.apk -- fedora40_dfs_sort_reverse with fedora40
	APKS match [OK] ^^
Output results in intermediates/apkdiff-results/base-xxhdpi.apk_fedora40_dfs_sort_reverse_vs_fedora40
=====================
Test #37: comparing base-xxhdpi.apk -- playstore with fedora40
['AndroidManifest.xml', 'resources.arsc']
Output results in intermediates/apkdiff-results/base-xxhdpi.apk_playstore_vs_fedora40
=====================

In [31]:
def extract_apk_comparison_results(pairs_df):
    """
    Compare APK pairs and collect comparison results into a DataFrame.

    Parameters:
    - pairs_df: DataFrame containing APK pairs to compare

    Returns:
    - results_df: DataFrame with comparison results
    """
    # Create base directories for results and mismatches
    apkdiff_result_path = pathlib.Path("intermediates/apkdiff-results")
    mismatch_folder = pathlib.Path("mismatches")

    # Clean up existing directories
    if apkdiff_result_path.exists() and apkdiff_result_path.is_dir():
        shutil.rmtree(apkdiff_result_path)
    apkdiff_result_path.mkdir(parents=True, exist_ok=True)

    if mismatch_folder.exists() and mismatch_folder.is_dir():
        shutil.rmtree(mismatch_folder)

    results = []

    for index, row in pairs_df.iterrows():
        r1, r2 = row["row_1_data"], row["row_2_data"]
        l1 = r1["os"] if r1["local_apk"] else "playstore"
        l2 = r2["os"] if r2["local_apk"] else "playstore"
        assert r1["filename"] == r2["filename"]

        # Create test index folder
        test_idx_folder = apkdiff_result_path / f"{r1['filename']}_{l1}_vs_{l2}"
        print(f"Test #{index+1}: comparing {r1['filename']} -- {l1} with {l2}")

        # Capture comparison output
        with io.StringIO() as buf, redirect_stdout(buf):
            res = ApkDiff().compare(r1["filepath"], r2["filepath"])
            output = buf.getvalue()

        # Prepare result dictionary
        result = {
            "pair": row["pair"],
            "filename": r1["filename"],
            "apk1_origin": l1,
            "apk2_origin": l2,
            "match": res,
            "match_reason": "apkdiff",
            "differences": None,
            "apk1_filepath": r1["filepath"],
            "apk2_filepath": r2["filepath"],
            "apk1_hash": r1["hash"],
            "apk2_hash": r2["hash"],
            "apk1_local": r1["local_apk"],
            "apk2_local": r2["local_apk"],
            "apk1_size": r1["size"],
            "apk2_size": r2["size"],
            "results_folder": str(test_idx_folder),
        }

        # If APKs don't match, move files and capture differences
        if not res:
            print("	APKs DON'T match [BAD]")

            # Regular expression to extract filenames with differences
            pattern = r"APKs differ on file ([\w/.-]+)!"
            differences = re.findall(pattern, output)
            result["differences"] = differences
            result["match_reason"] = None

            # Create test index folder and move mismatch files
            diff1_folder = mismatch_folder / "first"
            diff2_folder = mismatch_folder / "second"
            test_idx_folder.mkdir(parents=True, exist_ok=True)

            try:
                shutil.move(str(diff1_folder), str(test_idx_folder / "first"))
                shutil.move(str(diff2_folder), str(test_idx_folder / "second"))
            except Exception as e:
                print(f"Error moving mismatch files: {e}")

            print(f"	Mismatch files moved to {test_idx_folder}")
        else:
            print("	APKs match [OK]")

        print("=====================")

        results.append(result)

    # Clean up mismatch folder if it exists
    if mismatch_folder.exists() and mismatch_folder.is_dir():
        shutil.rmtree(mismatch_folder)

    # Convert results to DataFrame
    results_df = pd.DataFrame(results)

    return results_df

In [32]:
apkdiff_results = extract_apk_comparison_results(pairs_df)
###ADD previously seen results: that some artifacts match by hash
ub22_1 = df[(df["os"] == "ubuntu22") & (df["local_apk"])][
    ["os", "filename", "filepath", "hash", "size"]
]
ub22_2 = df[(df["os"] == "ubuntu22_dfs_sort") & (df["local_apk"])][
    ["os", "filename", "filepath", "hash", "size"]
]
ub22_3 = df[(df["os"] == "ubuntu22_dfs_sort_reverse") & (df["local_apk"])][
    ["os", "filename", "filepath", "hash", "size"]
]
ub22 = pd.concat([ub22_1, ub22_2, ub22_3])

f41_1 = df[(df["os"] == "fedora41") & (df["local_apk"])][
    ["os", "filename", "filepath", "hash", "size"]
]
f41_2 = df[(df["os"] == "fedora41_dfs_sort") & (df["local_apk"])][
    ["os", "filename", "filepath", "hash", "size"]
]
f41_3 = df[(df["os"] == "fedora41_dfs_sort_reverse") & (df["local_apk"])][
    ["os", "filename", "filepath", "hash", "size"]
]
f41 = pd.concat([f41_1, f41_2, f41_3])
merged_hashes = pd.merge(f41, ub22, on=["filename", "hash"], how="inner")
merged_hashes

extra_matches = {}


def create_match(filename: str, origin1, origin2, hash1, hash2, fp1, fp2, size1, size2):
    data = {
        "pair": (-1, -1),
        "filename": filename,
        "apk1_origin": origin1,
        "apk2_origin": origin2,
        "match": hash1 == hash2,
        "match_reason": "sha256",
        "differences": None,
        "apk1_filepath": fp1,
        "apk2_filepath": fp2,
        "apk1_hash": hash1,
        "apk2_hash": hash2,
        "apk1_local": True,
        "apk2_local": True,
        "apk1_size": size1,
        "apk2_size": size2,
        "results_folder": None,
    }
    apkdiff_results.loc[len(apkdiff_results)] = data


for index, row in merged_hashes.iterrows():
    create_match(
        row["filename"],
        row["os_x"],
        row["os_y"],
        row["hash"],
        row["hash"],
        row["filepath_x"],
        row["filepath_y"],
        row["size_x"],
        row["size_y"],
    )
print("apkdiff dataframe is done, ready for analysis")

Test #1: comparing base-arm64_v8a.apk -- fedora40_dfs_sort_reverse with playstore
	APKs DON'T match [BAD]
	Mismatch files moved to intermediates/apkdiff-results/base-arm64_v8a.apk_fedora40_dfs_sort_reverse_vs_playstore
=====================
Test #2: comparing base-arm64_v8a.apk -- fedora40_dfs_sort_reverse with fedora40
	APKs match [OK]
=====================
Test #3: comparing base-arm64_v8a.apk -- fedora40_dfs_sort_reverse with fedora41
	APKs match [OK]
=====================
Test #4: comparing base-arm64_v8a.apk -- playstore with fedora40
	APKs DON'T match [BAD]
	Mismatch files moved to intermediates/apkdiff-results/base-arm64_v8a.apk_playstore_vs_fedora40
=====================
Test #5: comparing base-arm64_v8a.apk -- playstore with fedora41
	APKs DON'T match [BAD]
	Mismatch files moved to intermediates/apkdiff-results/base-arm64_v8a.apk_playstore_vs_fedora41
=====================
Test #6: comparing base-arm64_v8a.apk -- fedora40 with fedora41
	APKs match [OK]
=====================
Test #7: comparing base-master.apk -- fedora40_dfs_sort_reverse with fedora40_dfs_sort
	APKs DON'T match [BAD]
	Mismatch files moved to intermediates/apkdiff-results/base-master.apk_fedora40_dfs_sort_reverse_vs_fedora40_dfs_sort
=====================
Test #8: comparing base-master.apk -- fedora40_dfs_sort_reverse with playstore
	APKs DON'T match [BAD]
	Mismatch files moved to intermediates/apkdiff-results/base-master.apk_fedora40_dfs_sort_reverse_vs_playstore
=====================
Test #9: comparing base-master.apk -- fedora40_dfs_sort_reverse with fedora40
	APKs DON'T match [BAD]
	Mismatch files moved to intermediates/apkdiff-results/base-master.apk_fedora40_dfs_sort_reverse_vs_fedora40
=====================
Test #10: comparing base-master.apk -- fedora40_dfs_sort_reverse with fedora41
	APKs DON'T match [BAD]
	Mismatch files moved to intermediates/apkdiff-results/base-master.apk_fedora40_dfs_sort_reverse_vs_fedora41
=====================
Test #11: comparing base-master.apk -- fedora40_dfs_sort_reverse with ubuntu22_dfs_sort_reverse
	APKs DON'T match [BAD]
	Mismatch files moved to intermediates/apkdiff-results/base-master.apk_fedora40_dfs_sort_reverse_vs_ubuntu22_dfs_sort_reverse
=====================
Test #12: comparing base-master.apk -- fedora40_dfs_sort_reverse with ubuntu22_dfs_sort
	APKs DON'T match [BAD]
	Mismatch files moved to intermediates/apkdiff-results/base-master.apk_fedora40_dfs_sort_reverse_vs_ubuntu22_dfs_sort
=====================
Test #13: comparing base-master.apk -- fedora40_dfs_sort_reverse with ubuntu22
	APKs DON'T match [BAD]
	Mismatch files moved to intermediates/apkdiff-results/base-master.apk_fedora40_dfs_sort_reverse_vs_ubuntu22
=====================
Test #14: comparing base-master.apk -- fedora40_dfs_sort with playstore
	APKs DON'T match [BAD]
	Mismatch files moved to intermediates/apkdiff-results/base-master.apk_fedora40_dfs_sort_vs_playstore
=====================
Test #15: comparing base-master.apk -- fedora40_dfs_sort with fedora40
	APKs DON'T match [BAD]
	Mismatch files moved to intermediates/apkdiff-results/base-master.apk_fedora40_dfs_sort_vs_fedora40
=====================
Test #16: comparing base-master.apk -- fedora40_dfs_sort with fedora41
	APKs DON'T match [BAD]
	Mismatch files moved to intermediates/apkdiff-results/base-master.apk_fedora40_dfs_sort_vs_fedora41
=====================
Test #17: comparing base-master.apk -- fedora40_dfs_sort with ubuntu22_dfs_sort_reverse
	APKs DON'T match [BAD]
	Mismatch files moved to intermediates/apkdiff-results/base-master.apk_fedora40_dfs_sort_vs_ubuntu22_dfs_sort_reverse
=====================
Test #18: comparing base-master.apk -- fedora40_dfs_sort with ubuntu22_dfs_sort
	APKs DON'T match [BAD]
	Mismatch files moved to intermediates/apkdiff-results/base-master.apk_fedora40_dfs_sort_vs_ubuntu22_dfs_sort
=====================
Test #19: comparing base-master.apk -- fedora40_dfs_sort with ubuntu22
	APKs DON'T match [BAD]
	Mismatch files moved to intermediates/apkdiff-results/base-master.apk_fedora40_dfs_sort_vs_ubuntu22
=====================
Test #20: comparing base-master.apk -- playstore with fedora40
	APKs DON'T match [BAD]
	Mismatch files moved to intermediates/apkdiff-results/base-master.apk_playstore_vs_fedora40
=====================
Test #21: comparing base-master.apk -- playstore with fedora41
	APKs DON'T match [BAD]
	Mismatch files moved to intermediates/apkdiff-results/base-master.apk_playstore_vs_fedora41
=====================
Test #22: comparing base-master.apk -- playstore with ubuntu22_dfs_sort_reverse
	APKs DON'T match [BAD]
	Mismatch files moved to intermediates/apkdiff-results/base-master.apk_playstore_vs_ubuntu22_dfs_sort_reverse
=====================
Test #23: comparing base-master.apk -- playstore with ubuntu22_dfs_sort
	APKs DON'T match [BAD]
	Mismatch files moved to intermediates/apkdiff-results/base-master.apk_playstore_vs_ubuntu22_dfs_sort
=====================
Test #24: comparing base-master.apk -- playstore with ubuntu22
	APKs DON'T match [BAD]
	Mismatch files moved to intermediates/apkdiff-results/base-master.apk_playstore_vs_ubuntu22
=====================
Test #25: comparing base-master.apk -- fedora40 with fedora41
	APKs match [OK]
=====================
Test #26: comparing base-master.apk -- fedora40 with ubuntu22_dfs_sort_reverse
	APKs DON'T match [BAD]
	Mismatch files moved to intermediates/apkdiff-results/base-master.apk_fedora40_vs_ubuntu22_dfs_sort_reverse
=====================
Test #27: comparing base-master.apk -- fedora40 with ubuntu22_dfs_sort
	APKs DON'T match [BAD]
	Mismatch files moved to intermediates/apkdiff-results/base-master.apk_fedora40_vs_ubuntu22_dfs_sort
=====================
Test #28: comparing base-master.apk -- fedora40 with ubuntu22
	APKs DON'T match [BAD]
	Mismatch files moved to intermediates/apkdiff-results/base-master.apk_fedora40_vs_ubuntu22
=====================
Test #29: comparing base-master.apk -- fedora41 with ubuntu22_dfs_sort_reverse
	APKs DON'T match [BAD]
	Mismatch files moved to intermediates/apkdiff-results/base-master.apk_fedora41_vs_ubuntu22_dfs_sort_reverse
=====================
Test #30: comparing base-master.apk -- fedora41 with ubuntu22_dfs_sort
	APKs DON'T match [BAD]
	Mismatch files moved to intermediates/apkdiff-results/base-master.apk_fedora41_vs_ubuntu22_dfs_sort
=====================
Test #31: comparing base-master.apk -- fedora41 with ubuntu22
	APKs DON'T match [BAD]
	Mismatch files moved to intermediates/apkdiff-results/base-master.apk_fedora41_vs_ubuntu22
=====================
Test #32: comparing base-master.apk -- ubuntu22_dfs_sort_reverse with ubuntu22_dfs_sort
	APKs DON'T match [BAD]
	Mismatch files moved to intermediates/apkdiff-results/base-master.apk_ubuntu22_dfs_sort_reverse_vs_ubuntu22_dfs_sort
=====================
Test #33: comparing base-master.apk -- ubuntu22_dfs_sort_reverse with ubuntu22
	APKs DON'T match [BAD]
	Mismatch files moved to intermediates/apkdiff-results/base-master.apk_ubuntu22_dfs_sort_reverse_vs_ubuntu22
=====================
Test #34: comparing base-master.apk -- ubuntu22_dfs_sort with ubuntu22
	APKs DON'T match [BAD]
	Mismatch files moved to intermediates/apkdiff-results/base-master.apk_ubuntu22_dfs_sort_vs_ubuntu22
=====================
Test #35: comparing base-xxhdpi.apk -- fedora40_dfs_sort_reverse with playstore
	APKs DON'T match [BAD]
	Mismatch files moved to intermediates/apkdiff-results/base-xxhdpi.apk_fedora40_dfs_sort_reverse_vs_playstore
=====================
Test #36: comparing base-xxhdpi.apk -- fedora40_dfs_sort_reverse with fedora40
	APKs match [OK]
=====================
Test #37: comparing base-xxhdpi.apk -- playstore with fedora40
	APKs DON'T match [BAD]
	Mismatch files moved to intermediates/apkdiff-results/base-xxhdpi.apk_playstore_vs_fedora40
=====================
apkdiff dataframe is done, ready for analysis

In [33]:
apkdiff_results.set_index(["filename", "pair"])
filtered = apkdiff_results.copy(deep=True)
filtered = filtered.filter(
    items=[
        "filename",
        "pair",
        "apk1_origin",
        "apk2_origin",
        "match",
        "match_reason",
        "differences",
    ]
)
filtered.head(1000)

,filename,pair,apk1_origin,apk2_origin,match,match_reason,differences
0,base-arm64_v8a.apk,"(0, 1)",fedora40_dfs_sort_reverse,playstore,False,None,[AndroidManifest.xml]
1,base-arm64_v8a.apk,"(0, 2)",fedora40_dfs_sort_reverse,fedora40,True,apkdiff,None
2,base-arm64_v8a.apk,"(0, 3)",fedora40_dfs_sort_reverse,fedora41,True,apkdiff,None
3,base-arm64_v8a.apk,"(1, 2)",playstore,fedora40,False,None,[AndroidManifest.xml]
4,base-arm64_v8a.apk,"(1, 3)",playstore,fedora41,False,None,[AndroidManifest.xml]
5,base-arm64_v8a.apk,"(2, 3)",fedora40,fedora41,True,apkdiff,None
6,base-master.apk,"(4, 5)",fedora40_dfs_sort_reverse,fedora40_dfs_sort,False,None,"[assets/dexopt/baseline.prof, assets/dexopt/ba..."
7,base-master.apk,"(4, 6)",fedora40_dfs_sort_reverse,playstore,False,None,"[AndroidManifest.xml, assets/dexopt/baseline.p..."
8,base-master.apk,"(4, 7)",fedora40_dfs_sort_reverse,fedora40,False,None,"[AndroidManifest.xml, assets/dexopt/baseline.p..."
9,base-master.apk,"(4, 8)",fedora40_dfs_sort_reverse,fedora41,False,None,"[AndroidManifest.xml, assets/dexopt/baseline.p..."
10,base-master.apk,"(4, 9)",fedora40_dfs_sort_reverse,ubuntu22_dfs_sort_reverse,False,None,"[CDSI.proto, DecryptedGroups.proto, Groups.pro..."
11,base-master.apk,"(4, 10)",fedora40_dfs_sort_reverse,ubuntu22_dfs_sort,False,None,"[CDSI.proto, DecryptedGroups.proto, Groups.pro..."
12,base-master.apk,"(4, 11)",fedora40_dfs_sort_reverse,ubuntu22,False,None,"[AndroidManifest.xml, assets/dexopt/baseline.p..."
13,base-master.apk,"(5, 6)",fedora40_dfs_sort,playstore,False,None,"[AndroidManifest.xml, classes2.dex, classes3.d..."
14,base-master.apk,"(5, 7)",fedora40_dfs_sort,fedora40,False,None,"[AndroidManifest.xml, classes2.dex, classes3.d..."
15,base-master.apk,"(5, 8)",fedora40_dfs_sort,fedora41,False,None,"[AndroidManifest.xml, classes2.dex, classes3.d..."
16,base-master.apk,"(5, 9)",fedora40_dfs_sort,ubuntu22_dfs_sort_reverse,False,None,"[CDSI.proto, DecryptedGroups.proto, Groups.pro..."
17,base-master.apk,"(5, 10)",fedora40_dfs_sort,ubuntu22_dfs_sort,False,None,"[CDSI.proto, DecryptedGroups.proto, Groups.pro..."
18,base-master.apk,"(5, 11)",fedora40_dfs_sort,ubuntu22,False,None,"[AndroidManifest.xml, classes2.dex, classes3.d..."
19,base-master.apk,"(6, 7)",playstore,fedora40,False,None,"[AndroidManifest.xml, classes2.dex, classes3.d..."
20,base-master.apk,"(6, 8)",playstore,fedora41,False,None,"[AndroidManifest.xml, classes2.dex, classes3.d..."
21,base-master.apk,"(6, 9)",playstore,ubuntu22_dfs_sort_reverse,False,None,"[AndroidManifest.xml, CDSI.proto, DecryptedGro..."
22,base-master.apk,"(6, 10)",playstore,ubuntu22_dfs_sort,False,None,"[AndroidManifest.xml, CDSI.proto, DecryptedGro..."
23,base-master.apk,"(6, 11)",playstore,ubuntu22,False,None,"[AndroidManifest.xml, classes3.dex, classes4.d..."
24,base-master.apk,"(7, 8)",fedora40,fedora41,True,apkdiff,None
25,base-master.apk,"(7, 9)",fedora40,ubuntu22_dfs_sort_reverse,False,None,"[AndroidManifest.xml, CDSI.proto, DecryptedGro..."
26,base-master.apk,"(7, 10)",fedora40,ubuntu22_dfs_sort,False,None,"[AndroidManifest.xml, CDSI.proto, DecryptedGro..."
27,base-master.apk,"(7, 11)",fedora40,ubuntu22,False,None,"[classes2.dex, classes3.dex, classes4.dex, cla..."
28,base-master.apk,"(8, 9)",fedora41,ubuntu22_dfs_sort_reverse,False,None,"[AndroidManifest.xml, CDSI.proto, DecryptedGro..."
29,base-master.apk,"(8, 10)",fedora41,ubuntu22_dfs_sort,False,None,"[AndroidManifest.xml, CDSI.proto, DecryptedGro..."
30,base-master.apk,"(8, 11)",fedora41,ubuntu22,False,None,"[classes2.dex, classes3.dex, classes4.dex, cla..."
31,base-master.apk,"(9, 10)",ubuntu22_dfs_sort_reverse,ubuntu22_dfs_sort,False,None,"[assets/dexopt/baseline.prof, assets/dexopt/ba..."
32,base-master.apk,"(9, 11)",ubuntu22_dfs_sort_reverse,ubuntu22,False,None,"[AndroidManifest.xml, CDSI.proto, DecryptedGro..."
33,base-master.apk,"(10, 11)",ubuntu22_dfs_sort,ubuntu22,False,None,"[AndroidManifest.xml, CDSI.proto, DecryptedGro..."
34,base-xxhdpi.apk,"(12, 13)",fedora40_dfs_sort_reverse,playstore,False,None,"[AndroidManifest.xml, resources.arsc]"
35,base-xxhdpi.apk,"(12, 14)",fedora40_dfs_sort_reverse,fedora40,True,apkdiff,None
36,base-xxhdpi.apk,"(13, 14)",playstore,fedora40,False,None,"[AndroidManifest.xml, resources.arsc]"
37,base-arm64_v8a.apk,"(-1, -1)",fedora41,ubuntu22,True,sha256,None
38,base-xxhdpi.apk,"(-1, -1)",fedora41,ubuntu22,True,sha256,None
39,base-xxhdpi.apk,"(-1, -1)",fedora41,ubuntu22_dfs_sort,True,sha256,None
40,base-xxhdpi.apk,"(-1, -1)",fedora41,ubuntu22_dfs_sort_reverse,True,sha256,None
41,base-arm64_v8a.apk,"(-1, -1)",fedora41_dfs_sort,ubuntu22_dfs_sort,True,sha256,None
42,base-arm64_v8a.apk,"(-1, -1)",fedora41_dfs_sort,ubuntu22_dfs_sort_reverse,True,sha256,None
43,base-xxhdpi.apk,"(-1, -1)",fedora41_dfs_sort,ubuntu22,True,sha256,None
44,base-xxhdpi.apk,"(-1, -1)",fedora41_dfs_sort,ubuntu22_dfs_sort,True,sha256,None
45,base-xxhdpi.apk,"(-1, -1)",fedora41_dfs_sort,ubuntu22_dfs_sort_reverse,True,sha256,None
46,base-arm64_v8a.apk,"(-1, -1)",fedora41_dfs_sort_reverse,ubuntu22_dfs_sort,True,sha256,None
47,base-arm64_v8a.apk,"(-1, -1)",fedora41_dfs_sort_reverse,ubuntu22_dfs_sort_reverse,True,sha256,None
48,base-xxhdpi.apk,"(-1, -1)",fedora41_dfs_sort_reverse,ubuntu22,True,sha256,None
49,base-xxhdpi.apk,"(-1, -1)",fedora41_dfs_sort_reverse,ubuntu22_dfs_sort,True,sha256,None
50,base-xxhdpi.apk,"(-1, -1)",fedora41_dfs_sort_reverse,ubuntu22_dfs_sort_reverse,True,sha256,None

> Did anyone match the playstore apk?

In [34]:
matches_playstore = apkdiff_results[
    (
        apkdiff_results["match"]
        & (apkdiff_results["apk1_local"] ^ apkdiff_results["apk2_local"])
    )
].set_index(["filename"])
if matches_playstore.size == 0:
    print("No local (split) apk matched playstore (split) apk")
matches_playstore

No local (split) apk matched playstore (split) apk

Empty DataFrame
Columns: [pair, apk1_origin, apk2_origin, match, match_reason, differences, apk1_filepath, apk2_filepath, apk1_hash, apk2_hash, apk1_local, apk2_local, apk1_size, apk2_size, results_folder]
Index: []

> No luck :c

In [35]:
apkdiff_results[
    (
        apkdiff_results["match"]
        & (apkdiff_results["apk1_local"] & apkdiff_results["apk2_local"])
    )
].set_index(["filename"])

,pair,apk1_origin,apk2_origin,match,match_reason,differences,apk1_filepath,apk2_filepath,apk1_hash,apk2_hash,apk1_local,apk2_local,apk1_size,apk2_size,results_folder
filename,,,,,,,,,,,,,,,
base-arm64_v8a.apk,"(0, 2)",fedora40_dfs_sort_reverse,fedora40,True,apkdiff,None,data/runs/fedora40_dfs_sort_reverse-scripted/a...,data/runs/fedora40-manual/apks-i-built/base-ar...,995c37061435d46d5f3d7caf4fe7e1817a8b9a0d4049a7...,a74d526fd13f4fe3bda7e066c575fa0c931d8da7333b8d...,True,True,10699335,23561264,intermediates/apkdiff-results/base-arm64_v8a.a...
base-arm64_v8a.apk,"(0, 3)",fedora40_dfs_sort_reverse,fedora41,True,apkdiff,None,data/runs/fedora40_dfs_sort_reverse-scripted/a...,data/runs/fedora41-scripted-1/apks-i-built/bas...,995c37061435d46d5f3d7caf4fe7e1817a8b9a0d4049a7...,4832f3a837a4059db7476c45d995045b0c561388234335...,True,True,10699335,23552089,intermediates/apkdiff-results/base-arm64_v8a.a...
base-arm64_v8a.apk,"(2, 3)",fedora40,fedora41,True,apkdiff,None,data/runs/fedora40-manual/apks-i-built/base-ar...,data/runs/fedora41-scripted-1/apks-i-built/bas...,a74d526fd13f4fe3bda7e066c575fa0c931d8da7333b8d...,4832f3a837a4059db7476c45d995045b0c561388234335...,True,True,23561264,23552089,intermediates/apkdiff-results/base-arm64_v8a.a...
base-master.apk,"(7, 8)",fedora40,fedora41,True,apkdiff,None,data/runs/fedora40-manual/apks-i-built/base-ma...,data/runs/fedora41-scripted-1/apks-i-built/bas...,4768602685c6e5ceff078093c87e9aba5f19597b0d76c5...,dbe76a3649f90f061170c6d3d2071bcddc3c32672bebc2...,True,True,85021050,84693087,intermediates/apkdiff-results/base-master.apk_...
base-xxhdpi.apk,"(12, 14)",fedora40_dfs_sort_reverse,fedora40,True,apkdiff,None,data/runs/fedora40_dfs_sort_reverse-scripted/a...,data/runs/fedora40-manual/apks-i-built/base-xx...,41b12629671ba0778364d671909add3a94380955c5c366...,51119b048c0e03525cbb253ed7c19974738b58804908d3...,True,True,1637689,1658464,intermediates/apkdiff-results/base-xxhdpi.apk_...
base-arm64_v8a.apk,"(-1, -1)",fedora41,ubuntu22,True,sha256,None,data/runs/fedora41-scripted-1/apks-i-built/bas...,data/runs/ubuntu22-scripted-1/apks-i-built/bas...,4832f3a837a4059db7476c45d995045b0c561388234335...,4832f3a837a4059db7476c45d995045b0c561388234335...,True,True,23552089,23552089,None
base-xxhdpi.apk,"(-1, -1)",fedora41,ubuntu22,True,sha256,None,data/runs/fedora41-scripted-1/apks-i-built/bas...,data/runs/ubuntu22-scripted-1/apks-i-built/bas...,41b12629671ba0778364d671909add3a94380955c5c366...,41b12629671ba0778364d671909add3a94380955c5c366...,True,True,1637689,1637689,None
base-xxhdpi.apk,"(-1, -1)",fedora41,ubuntu22_dfs_sort,True,sha256,None,data/runs/fedora41-scripted-1/apks-i-built/bas...,data/runs/ubuntu22_dfs_sort-scripted/apks-i-bu...,41b12629671ba0778364d671909add3a94380955c5c366...,41b12629671ba0778364d671909add3a94380955c5c366...,True,True,1637689,1637689,None
base-xxhdpi.apk,"(-1, -1)",fedora41,ubuntu22_dfs_sort_reverse,True,sha256,None,data/runs/fedora41-scripted-1/apks-i-built/bas...,data/runs/ubuntu22_dfs_sort_reverse-scripted/a...,41b12629671ba0778364d671909add3a94380955c5c366...,41b12629671ba0778364d671909add3a94380955c5c366...,True,True,1637689,1637689,None
base-arm64_v8a.apk,"(-1, -1)",fedora41_dfs_sort,ubuntu22_dfs_sort,True,sha256,None,data/runs/fedora41_dfs_sort-scripted/apks-i-bu...,data/runs/ubuntu22_dfs_sort-scripted/apks-i-bu...,995c37061435d46d5f3d7caf4fe7e1817a8b9a0d4049a7...,995c37061435d46d5f3d7caf4fe7e1817a8b9a0d4049a7...,True,True,10699335,10699335,None
base-arm64_v8a.apk,"(-1, -1)",fedora41_dfs_sort,ubuntu22_dfs_sort_reverse,True,sha256,None,data/runs/fedora41_dfs_sort-scripted/apks-i-bu...,data/runs/ubuntu22_dfs_sort_reverse-scripted/a...,995c37061435d46d5f3d7caf4fe7e1817a8b9a0d4049a7...,995c37061435d46d5f3d7caf4fe7e1817a8b9a0d4049a7...,True,True,10699335,10699335,None
base-xxhdpi.apk,"(-1, -1)",fedora41_dfs_sort,ubuntu22,True,sha256,None,data/runs/fedora41_dfs_sort-scripted/apks-i-bu...,data/runs/ubuntu22-scripted-1/apks-i-built/bas...,41b12629671ba0778364d671909add3a94380955c5c366...,41b12629671ba0778364d671909add3a94380955c5c366...,True,True,1637689,1637689,None
base-xxhdpi.apk,"(-1, -1)",fedora41_dfs_sort,ubuntu22_dfs_sort,True,sha256,None,data/runs/fedora41_dfs_sort-scripted/apks-i-bu...,data/runs/ubuntu22_dfs_sort-scripted/apks-i-bu...,41b12629671ba0778364d671909add3a94380955c5c366...,41b12629671ba0778364d671909add3a94380955c5c366...,True,True,1637689,1637689,None
base-xxhdpi.apk,"(-1, -1)",fedora41_dfs_sort,ubuntu22_dfs_sort_reverse,True,sha256,None,data/runs/fedora41_dfs_sort-scripted/apks-i-bu...,data/runs/ubuntu22_dfs_sort_reverse-scripted/a...,41b12629671ba0778364d671909add3a94380955c5c366...,41b12629671ba0778364d671909add3a94380955c5c366...,True,True,1637689,1637689,None
base-arm64_v8a.apk,"(-1, -1)",fedora41_dfs_sort_reverse,ubuntu22_dfs_sort,True,sha256,None,data/runs/fedora41_dfs_sort_reverse-scripted/a...,data/runs/ubuntu22_dfs_sort-scripted/apks-i-bu...,995c37061435d46d5f3d7caf4fe7e1817a8b9a0d4049a7...,995c37061435d46d5f3d7caf4fe7e1817a8b9a0d4049a7...,True,True,10699335,10699335,None
base-arm64_v8a.apk,"(-1, -1)",fedora41_dfs_sort_reverse,ubuntu22_dfs_sort_reverse,True,sha256,None,data/runs/fedora41_dfs_sort_reverse-scripted/a...,data/runs/ubuntu22_dfs_sort_reverse-scripted/a...,995c37061435d46d5f3d7caf4fe7e1817a8b9a0d4049a7...,995c37061435d46d5f3d7caf4fe7e1817a8b9a0d4049a7...,True,True,10699335,10699335,None
base-xxhdpi.apk,"(-1, -1)",fedora41_dfs_sort_reverse,ubuntu22,True,sha256,None,data/runs/fedora41_dfs_sort_reverse-scripted/a...,data/runs/ubuntu22-scripted-1/apks-i-built/bas...,41b12629671ba0778364d671909add3a94380955c5c366...,41b12629671ba0778364d671909add3a94380955c5c366...,True,True,1637689,1637689,None
base-xxhdpi.apk,"(-1, -1)",fedora41_dfs_sort_reverse,ubuntu22_dfs_sort,True,sha256,None,data/runs/fedora41_dfs_sort_reverse-scripted/a...,data/runs/ubuntu22_dfs_sort-scripted/apks-i-bu...,41b12629671ba0778364d671909add3a94380955c5c366...,41b12629671ba0778364d671909add3a94380955c5c366...,True,True,1637689,1637689,None
base-xxhdpi.apk,"(-1, -1)",fedora41_dfs_sort_reverse,ubuntu22_dfs_sort_reverse,True,sha256,None,data/runs/fedora41_dfs_sort_reverse-scripted/a...,data/runs/ubuntu22_dfs_sort_reverse-scripted/a...,41b12629671ba0778364d671909add3a94380955c5c366...,41b12629671ba0778364d671909add3a94380955c5c366...,True,True,1637689,1637689,None

So: `fedora41` and `fedora40` are reproducible (according to apkdiff). `base-master.apk` differs between ubuntu and fedora. either way, no one matches playstore :C

TODO: what tf is going on, run apkdiff on the matrix of diverging stuff and check

In [36]:
mismatched = apkdiff_results[~apkdiff_results["match"]]
mismatched

,pair,filename,apk1_origin,apk2_origin,match,match_reason,differences,apk1_filepath,apk2_filepath,apk1_hash,apk2_hash,apk1_local,apk2_local,apk1_size,apk2_size,results_folder
0,"(0, 1)",base-arm64_v8a.apk,fedora40_dfs_sort_reverse,playstore,False,None,[AndroidManifest.xml],data/runs/fedora40_dfs_sort_reverse-scripted/a...,data/runs/fedora40-manual/apks-from-device/bas...,995c37061435d46d5f3d7caf4fe7e1817a8b9a0d4049a7...,d296fff8691b3632f85725202045875af7e89dafedc9df...,True,False,10699335,23569519,intermediates/apkdiff-results/base-arm64_v8a.a...
3,"(1, 2)",base-arm64_v8a.apk,playstore,fedora40,False,None,[AndroidManifest.xml],data/runs/fedora40-manual/apks-from-device/bas...,data/runs/fedora40-manual/apks-i-built/base-ar...,d296fff8691b3632f85725202045875af7e89dafedc9df...,a74d526fd13f4fe3bda7e066c575fa0c931d8da7333b8d...,False,True,23569519,23561264,intermediates/apkdiff-results/base-arm64_v8a.a...
4,"(1, 3)",base-arm64_v8a.apk,playstore,fedora41,False,None,[AndroidManifest.xml],data/runs/fedora40-manual/apks-from-device/bas...,data/runs/fedora41-scripted-1/apks-i-built/bas...,d296fff8691b3632f85725202045875af7e89dafedc9df...,4832f3a837a4059db7476c45d995045b0c561388234335...,False,True,23569519,23552089,intermediates/apkdiff-results/base-arm64_v8a.a...
6,"(4, 5)",base-master.apk,fedora40_dfs_sort_reverse,fedora40_dfs_sort,False,None,"[assets/dexopt/baseline.prof, assets/dexopt/ba...",data/runs/fedora40_dfs_sort_reverse-scripted/a...,data/runs/fedora40_dfs_sort-scripted/apks-i-bu...,243e0a3b54cd8b21046155f7fccbe08def0a998f8ecdf0...,ed0c8b3e94ba72dc96920b55732c29dd8038c6446df5b0...,True,True,52381043,52380815,intermediates/apkdiff-results/base-master.apk_...
7,"(4, 6)",base-master.apk,fedora40_dfs_sort_reverse,playstore,False,None,"[AndroidManifest.xml, assets/dexopt/baseline.p...",data/runs/fedora40_dfs_sort_reverse-scripted/a...,data/runs/fedora40-manual/apks-from-device/bas...,243e0a3b54cd8b21046155f7fccbe08def0a998f8ecdf0...,eb1902b3aa98e15a140e9de574dfa47b78bf8bb85fc556...,True,False,52381043,85037580,intermediates/apkdiff-results/base-master.apk_...
8,"(4, 7)",base-master.apk,fedora40_dfs_sort_reverse,fedora40,False,None,"[AndroidManifest.xml, assets/dexopt/baseline.p...",data/runs/fedora40_dfs_sort_reverse-scripted/a...,data/runs/fedora40-manual/apks-i-built/base-ma...,243e0a3b54cd8b21046155f7fccbe08def0a998f8ecdf0...,4768602685c6e5ceff078093c87e9aba5f19597b0d76c5...,True,True,52381043,85021050,intermediates/apkdiff-results/base-master.apk_...
9,"(4, 8)",base-master.apk,fedora40_dfs_sort_reverse,fedora41,False,None,"[AndroidManifest.xml, assets/dexopt/baseline.p...",data/runs/fedora40_dfs_sort_reverse-scripted/a...,data/runs/fedora41-scripted-1/apks-i-built/bas...,243e0a3b54cd8b21046155f7fccbe08def0a998f8ecdf0...,dbe76a3649f90f061170c6d3d2071bcddc3c32672bebc2...,True,True,52381043,84693087,intermediates/apkdiff-results/base-master.apk_...
10,"(4, 9)",base-master.apk,fedora40_dfs_sort_reverse,ubuntu22_dfs_sort_reverse,False,None,"[CDSI.proto, DecryptedGroups.proto, Groups.pro...",data/runs/fedora40_dfs_sort_reverse-scripted/a...,data/runs/ubuntu22_dfs_sort_reverse-scripted/a...,243e0a3b54cd8b21046155f7fccbe08def0a998f8ecdf0...,11b479c5082ca4323ab811d05288283f079f881f665619...,True,True,52381043,52381531,intermediates/apkdiff-results/base-master.apk_...
11,"(4, 10)",base-master.apk,fedora40_dfs_sort_reverse,ubuntu22_dfs_sort,False,None,"[CDSI.proto, DecryptedGroups.proto, Groups.pro...",data/runs/fedora40_dfs_sort_reverse-scripted/a...,data/runs/ubuntu22_dfs_sort-scripted/apks-i-bu...,243e0a3b54cd8b21046155f7fccbe08def0a998f8ecdf0...,391c7b876ff6aa67b5922f3699c17f3beb21ff0913ba6a...,True,True,52381043,52381303,intermediates/apkdiff-results/base-master.apk_...
12,"(4, 11)",base-master.apk,fedora40_dfs_sort_reverse,ubuntu22,False,None,"[AndroidManifest.xml, assets/dexopt/baseline.p...",data/runs/fedora40_dfs_sort_reverse-scripted/a...,data/runs/ubuntu22-scripted-1/apks-i-built/bas...,243e0a3b54cd8b21046155f7fccbe08def0a998f8ecdf0...,fa1e7eec6dc3e634aae9ccba817d04db46b46c10ca4556...,True,True,52381043,84693087,intermediates/apkdiff-results/base-master.apk_...
13,"(5, 6)",base-master.apk,fedora40_dfs_sort,playstore,False,None,"[AndroidManifest.xml, classes2.dex, classes3.d...",data/runs/fedora40_dfs_sort-scripted/apks-i-bu...,data/runs/fedora40-manual/apks-from-device/bas...,ed0c8b3e94ba72dc96920b55732c29dd8038c6446df5b0...,eb1902b3aa98e15a140e9de574dfa47b78bf8bb85fc556...,True,False,52380815,85037580,intermediates/apkdiff-results/base-master.apk_...
14,"(5, 7)",base-master.apk,fedora40_dfs_sort,fedora40,False,None,"[AndroidManifest.xml, classes2.dex, classes3.d...",data/runs/fedora40_dfs_sort-scripted/apks-i-bu...,data/runs/fedora40-manual/apks-i-built/base-ma...,ed0c8b3e94ba72dc96920b55732c29dd8038c6446df5b0...,4768602685c6e5ceff078093c87e9aba5f19597b0d76c5...,True,True,52380815,85021050,intermediates/apkdiff-results/base-master.apk_...
15,"(5, 8)",base-master.apk,fedora40_dfs_sort,fedora41,False,None,"[AndroidManifest.xml, classes2.dex, classes3.d...",data/runs/fedora40_dfs_sort-scripted/apks-i-bu...,data/runs/fedora41-scripted-1/apks-i-built/bas...,ed0c8b3e94ba72dc96920b55732c29dd8038c6446df5b0...,dbe76a3649f90f061170c6d3d2071bcddc3c32672bebc2...,True,True,52380815,84693087,intermediates/apkdiff-results/base-master.apk_...
16,"(5, 9)",base-master.apk,fedora40_dfs_sort,ubuntu22_dfs_sort_reverse,False,None,"[CDSI.proto, DecryptedGroups.proto, Groups.pro...",data/runs/fedora40_dfs_sort-scripted/apks-i-bu...,data/runs/ubuntu22_dfs_sort_reverse-scripted/a...,ed0c8b3e94ba72dc96920b55732c29dd8038c6446df5b0...,11b479c5082ca4323ab811d05288283f079f881f665619...,True,True,52380815,52381531,intermediates/apkdiff-results/base-master.apk_...
17,"(5, 10)",base-master.apk,fedora40_dfs_sort,ubuntu22_dfs_sort,False,None,"[CDSI.proto, DecryptedGroups.proto, Groups.pro...",data/runs/fedora40_dfs_sort-scripted/apks-i-bu...,data/runs/ubuntu22_dfs_sort-scripted/apks-i-bu...,ed0c8b3e94ba72dc96920b55732c29dd8038c6446df5b0...,391c7b876ff6aa67b5922f3699c17f3beb21ff0913ba6a...,True,True,52380815,52381303,intermediates/apkdiff-results/base-master.apk_...
18,"(5, 11)",base-master.apk,fedora40_dfs_sort,ubuntu22,False,None,"[AndroidManifest.xml, classes2.dex, classes3.d...",data/runs/fedora40_dfs_sort-scripted/apks-i-bu...,data/runs/ubuntu22-scripted-1/apks-i-built/bas...,ed0c8b3e94ba72dc96920b55732c29dd8038c6446df5b0...,fa1e7eec6dc3e634aae9ccba817d04db46b46c10ca4556...,True,True,52380815,84693087,intermediates/apkdiff-results/base-master.apk_...
19,"(6, 7)",base-master.apk,playstore,fedora40,False,None,"[AndroidManifest.xml, classes2.dex, classes3.d...",data/runs/fedora40-manual/apks-from-device/bas...,data/runs/fedora40-manual/apks-i-built/base-ma...,eb1902b3aa98e15a140e9de574dfa47b78bf8bb85fc556...,4768602685c6e5ceff078093c87e9aba5f19597b0d76c5...,False,True,85037580,85021050,intermediates/apkdiff-results/base-master.apk_...
20,"(6, 8)",base-master.apk,playstore,fedora41,False,None,"[AndroidManifest.xml, classes2.dex, classes3.d...",data/runs/fedora40-manual/apks-from-device/bas...,data/runs/fedora41-scripted-1/apks-i-built/bas...,eb1902b3aa98e15a140e9de574dfa47b78bf8bb85fc556...,dbe76a3649f90f061170c6d3d2071bcddc3c32672bebc2...,False,True,85037580,84693087,intermediates/apkdiff-results/base-master.apk_...
21,"(6, 9)",base-master.apk,playstore,ubuntu22_dfs_sort_reverse,False,None,"[AndroidManifest.xml, CDSI.proto, DecryptedGro...",data/runs/fedora40-manual/apks-from-device/bas...,data/runs/ubuntu22_dfs_sort_reverse-scripted/a...,eb1902b3aa98e15a140e9de574dfa47b78bf8bb85fc556...,11b479c5082ca4323ab811d05288283f079f881f665619...,False,True,85037580,52381531,intermediates/apkdiff-results/base-master.apk_...
22,"(6, 10)",base-master.apk,playstore,ubuntu22_dfs_sort,False,None,"[AndroidManifest.xml, CDSI.proto, DecryptedGro...",data/runs/fedora40-manual/apks-from-device/bas...,data/runs/ubuntu22_dfs_sort-scripted/apks-i-bu...,eb1902b3aa98e15a140e9de574dfa47b78bf8bb85fc556...,391c7b876ff6aa67b5922f3699c17f3beb21ff0913ba6a...,False,True,85037580,52381303,intermediates/apkdiff-results/base-master.apk_...
23,"(6, 11)",base-master.apk,playstore,ubuntu22,False,None,"[AndroidManifest.xml, classes3.dex, classes4.d...",data/runs/fedora40-manual/apks-from-device/bas...,data/runs/ubuntu22-scripted-1/apks-i-built/bas...,eb1902b3aa98e15a140e9de574dfa47b78bf8bb85fc556...,fa1e7eec6dc3e634aae9ccba817d04db46b46c10ca4556...,False,True,85037580,84693087,intermediates/apkdiff-results/base-master.apk_...
25,"(7, 9)",base-master.apk,fedora40,ubuntu22_dfs_sort_reverse,False,None,"[AndroidManifest.xml, CDSI.proto, DecryptedGro...",data/runs/fedora40-manual/apks-i-built/base-ma...,data/runs/ubuntu22_dfs_sort_reverse-scripted/a...,4768602685c6e5ceff078093c87e9aba5f19597b0d76c5...,11b479c5082ca4323ab811d05288283f079f881f665619...,True,True,85021050,52381531,intermediates/apkdiff-results/base-master.apk_...
26,"(7, 10)",base-master.apk,fedora40,ubuntu22_dfs_sort,False,None,"[AndroidManifest.xml, CDSI.proto, DecryptedGro...",data/runs/fedora40-manual/apks-i-built/base-ma...,data/runs/ubuntu22_dfs_sort-scripted/apks-i-bu...,4768602685c6e5ceff078093c87e9aba5f19597b0d76c5...,391c7b876ff6aa67b5922f3699c17f3beb21ff0913ba6a...,True,True,85021050,52381303,intermediates/apkdiff-results/base-master.apk_...
27,"(7, 11)",base-master.apk,fedora40,ubuntu22,False,None,"[classes2.dex, classes3.dex, classes4.dex, cla...",data/runs/fedora40-manual/apks-i-built/base-ma...,data/runs/ubuntu22-scripted-1/apks-i-built/bas...,4768602685c6e5ceff078093c87e9aba5f19597b0d76c5...,fa1e7eec6dc3e634aae9ccba817d04db46b46c10ca4556...,True,True,85021050,84693087,intermediates/apkdiff-results/base-master.apk_...
28,"(8, 9)",base-master.apk,fedora41,ubuntu22_dfs_sort_reverse,False,None,"[AndroidManifest.xml, CDSI.proto, DecryptedGro...",data/runs/fedora41-scripted-1/apks-i-built/bas...,data/runs/ubuntu22_dfs_sort_reverse-scripted/a...,dbe76a3649f90f061170c6d3d2071bcddc3c32672bebc2...,11b479c5082ca4323ab811d05288283f079f881f665619...,True,True,84693087,52381531,intermediates/apkdiff-results/base-master.apk_...
29,"(8, 10)",base-master.apk,fedora41,ubuntu22_dfs_sort,False,None,"[AndroidManifest.xml, CDSI.proto, DecryptedGro...",data/runs/fedora41-scripted-1/apks-i-built/bas...,data/runs/ubuntu22_dfs_sort-scripted/apks-i-bu...,dbe76a3649f90f061170c6d3d2071bcddc3c32672bebc2...,391c7b876ff6aa67b5922f3699c17f3beb21ff0913ba6a...,True,True,84693087,52381303,intermediates/apkdiff-results/base-master.apk_...
30,"(8, 11)",base-master.apk,fedora41,ubuntu22,False,None,"[classes2.dex, classes3.dex, classes4.dex, cla...",data/runs/fedora41-scripted-1/apks-i-built/bas...,data/runs/ubuntu22-scripted-1/apks-i-built/bas...,dbe76a3649f90f061170c6d3d2071bcddc3c32672bebc2...,fa1e7eec6dc3e634aae9ccba817d04db46b46c10ca4556...,True,True,84693087,84693087,intermediates/apkdiff-results/base-master.apk_...
31,"(9, 10)",base-master.apk,ubuntu22_dfs_sort_reverse,ubuntu22_dfs_sort,False,None,"[assets/dexopt/baseline.prof, assets/dexopt/ba...",data/runs/ubuntu22_dfs_sort_reverse-scripted/a...,data/runs/ubuntu22_dfs_sort-scripted/apks-i-bu...,11b479c5082ca4323ab811d05288283f079f881f665619...,391c7b876ff6aa67b5922f3699c17f3beb21ff0913ba6a...,True,True,52381531,52381303,intermediates/apkdiff-results/base-master.apk_...
32,"(9, 11)",base-master.apk,ubuntu22_dfs_sort_reverse,ubuntu22,False,None,"[AndroidManifest.xml, CDSI.proto, DecryptedGro...",data/runs/ubuntu22_dfs_sort_reverse-scripted/a...,data/runs/ubuntu22-scripted-1/apks-i-built/bas...,11b479c5082ca4323ab811d05288283f079f881f665619...,fa1e7eec6dc3e634aae9ccba817d04db46b46c10ca4556...,True,True,52381531,84693087,intermediates/apkdiff-results/base-master.apk_...
33,"(10, 11)",base-master.apk,ubuntu22_dfs_sort,ubuntu22,False,None,"[AndroidManifest.xml, CDSI.proto, DecryptedGro...",data/runs/ubuntu22_dfs_sort-scripted/apks-i-bu...,data/runs/ubuntu22-scripted-1/apks-i-built/bas...,391c7b876ff6aa67b5922f3699c17f3beb21ff0913ba6a...,fa1e7eec6dc3e634aae9ccba817d04db46b46c10ca4556...,True,True,52381303,84693087,intermediates/apkdiff-results/base-master.apk_...
34,"(12, 13)",base-xxhdpi.apk,fedora40_dfs_sort_reverse,playstore,False,None,"[AndroidManifest.xml, resources.arsc]",data/runs/fedora40_dfs_sort_reverse-scripted/a...,data/runs/fedora40-manual/apks-from-device/bas...,41b12629671ba0778364d671909add3a94380955c5c366...,c65a2691cde28650f8934d492bff6c241b2e55eee4d222...,True,False,1637689,1666719,intermediates/apkdiff-results/base-xxhdpi.apk_...
36,"(13, 14)",base-xxhdpi.apk,playstore,fedora40,False,None,"[AndroidManifest.xml, resources.arsc]",data/runs/fedora40-manual/apks-from-device/bas...,data/runs/fedora40-manual/apks-i-built/base-xx...,c65a2691cde28650f8934d492bff6c241b2e55eee4d222...,51119b048c0e03525cbb253ed7c19974738b58804908d3...,False,True,1666719,1658464,intermediates/apkdiff-results/base-xxhdpi.apk_...

## Diffuse

In [37]:
import zipfile

import requests

In [38]:
# Create directories
diffuse_dir = pathlib.Path("tools/diffuse")
diffuse_dir.mkdir(parents=True, exist_ok=True)

diffuse_results_dir = pathlib.Path("intermediates/diffuse-results")
diffuse_results_dir.mkdir(parents=True, exist_ok=True)
## Download diffuse manually and put it there:
# https://github.com/JakeWharton/diffuse/releases/latest

In [43]:
!./tools/diffuse/bin/diffuse diff -h

Usage: diffuse diff [<options>] <old> <new>

  Display changes between two binaries.

Input options:
  --apk, --aar, --aab, --jar, --dex  Input file type. Default is 'apk'.
  --old-mapping=<file>               Mapping file produced by R8 or ProGuard.
  --new-mapping=<file>               Mapping file produced by R8 or ProGuard.

Output options:
  --text=<file>         File to write text report. Note: Specifying this option
                        will disable printing the text report to standard out by
                        default. Specify '--stdout text' to restore that
                        behavior.
  --html=<file>         File to write HTML report. Note: Specifying this option
                        will disable printing the text report to standard out by
                        default. Specify '--stdout text' to restore that
                        behavior.
  --stdout=(text|html)  Report to print to standard out. By default, The text
                        report will be printed to standard out ONLY when neither
                        --text nor --html are specified.

Options:
  -h, --help  Show this message and exit

Arguments:
  <old>  Old input file.
  <new>  New input file.

In [44]:
import subprocess
from contextlib import redirect_stderr, redirect_stdout

In [45]:
mismatched[~(mismatched["filename"].str.contains("arm"))].shape

(29, 16)

In [46]:
# for index, row in mismatched[mismatched["filename"].str.contains("master")].iterrows():
#
# diffuse can only compare the apk that has a resources.arsc entry
for index, row in mismatched[~(mismatched["filename"].str.contains("arm"))].iterrows():
    print("==============================")
    print(
        f"./diffuse check between {row['filename']} {row['apk1_origin']} ({row['apk1_filepath']}) and {row['apk2_origin']} ({row['apk2_filepath']})"
    )
    name = (
        f"diffuse_{row['filename']}__{row['apk1_origin']}_vs_{row['apk2_origin']}.txt"
    )

    output_buffer = io.StringIO()
    result_file_path = str(diffuse_results_dir / name)

    # with redirect_stdout(output_buffer):
    try:
        # Run the diffuse command and redirect stdout to the buffer
        output = subprocess.check_output(
            [
                "./tools/diffuse/bin/diffuse",
                "diff",
                row["apk1_filepath"],
                row["apk2_filepath"],
            ],
            stderr=subprocess.STDOUT,
        )

        output = output.decode(
            "utf-8"
        ).strip()  # Decode the byte output to string and strip any leading/trailing whitespace
        print(len(output))
        # Check if the output is empty
        if not output:
            print(f"The output file {name} is empty.")
        else:
            # Replace "OLD" and "NEW" APK names in the output
            output = output.replace(
                f"OLD: {row['filename']}", f"OLD: {row['apk1_filepath']}"
            )
            output = output.replace(
                f"NEW: {row['filename']}", f"NEW: {row['apk2_filepath']}"
            )

            with open(result_file_path, "w") as file:
                file.write(output)
                # print(
                #     f"Captured output from the command: {output[:100]}..."
                # )  # Print first 100 characters of captured output
        # break
    except subprocess.CalledProcessError as e:
        print(f"An error occurred while running diffuse for {row['filename']}: {e}")

==============================
./diffuse check between base-master.apk fedora40_dfs_sort_reverse (data/runs/fedora40_dfs_sort_reverse-scripted/apks-i-built/base-master.apk) and fedora40_dfs_sort (data/runs/fedora40_dfs_sort-scripted/apks-i-built/base-master.apk)
3997
==============================
./diffuse check between base-master.apk fedora40_dfs_sort_reverse (data/runs/fedora40_dfs_sort_reverse-scripted/apks-i-built/base-master.apk) and playstore (data/runs/fedora40-manual/apks-from-device/base-master.apk)
6363
==============================
./diffuse check between base-master.apk fedora40_dfs_sort_reverse (data/runs/fedora40_dfs_sort_reverse-scripted/apks-i-built/base-master.apk) and fedora40 (data/runs/fedora40-manual/apks-i-built/base-master.apk)
5247
==============================
./diffuse check between base-master.apk fedora40_dfs_sort_reverse (data/runs/fedora40_dfs_sort_reverse-scripted/apks-i-built/base-master.apk) and fedora41 (data/runs/fedora41-scripted-1/apks-i-built/base-master.apk)
4626
==============================
./diffuse check between base-master.apk fedora40_dfs_sort_reverse (data/runs/fedora40_dfs_sort_reverse-scripted/apks-i-built/base-master.apk) and ubuntu22_dfs_sort_reverse (data/runs/ubuntu22_dfs_sort_reverse-scripted/apks-i-built/base-master.apk)
3700
==============================
./diffuse check between base-master.apk fedora40_dfs_sort_reverse (data/runs/fedora40_dfs_sort_reverse-scripted/apks-i-built/base-master.apk) and ubuntu22_dfs_sort (data/runs/ubuntu22_dfs_sort-scripted/apks-i-built/base-master.apk)
5654
==============================
./diffuse check between base-master.apk fedora40_dfs_sort_reverse (data/runs/fedora40_dfs_sort_reverse-scripted/apks-i-built/base-master.apk) and ubuntu22 (data/runs/ubuntu22-scripted-1/apks-i-built/base-master.apk)
4592
==============================
./diffuse check between base-master.apk fedora40_dfs_sort (data/runs/fedora40_dfs_sort-scripted/apks-i-built/base-master.apk) and playstore (data/runs/fedora40-manual/apks-from-device/base-master.apk)
5079
==============================
./diffuse check between base-master.apk fedora40_dfs_sort (data/runs/fedora40_dfs_sort-scripted/apks-i-built/base-master.apk) and fedora40 (data/runs/fedora40-manual/apks-i-built/base-master.apk)
3967
==============================
./diffuse check between base-master.apk fedora40_dfs_sort (data/runs/fedora40_dfs_sort-scripted/apks-i-built/base-master.apk) and fedora41 (data/runs/fedora41-scripted-1/apks-i-built/base-master.apk)
3325
==============================
./diffuse check between base-master.apk fedora40_dfs_sort (data/runs/fedora40_dfs_sort-scripted/apks-i-built/base-master.apk) and ubuntu22_dfs_sort_reverse (data/runs/ubuntu22_dfs_sort_reverse-scripted/apks-i-built/base-master.apk)
5654
==============================
./diffuse check between base-master.apk fedora40_dfs_sort (data/runs/fedora40_dfs_sort-scripted/apks-i-built/base-master.apk) and ubuntu22_dfs_sort (data/runs/ubuntu22_dfs_sort-scripted/apks-i-built/base-master.apk)
3700
==============================
./diffuse check between base-master.apk fedora40_dfs_sort (data/runs/fedora40_dfs_sort-scripted/apks-i-built/base-master.apk) and ubuntu22 (data/runs/ubuntu22-scripted-1/apks-i-built/base-master.apk)
3325
==============================
./diffuse check between base-master.apk playstore (data/runs/fedora40-manual/apks-from-device/base-master.apk) and fedora40 (data/runs/fedora40-manual/apks-i-built/base-master.apk)
4723
==============================
./diffuse check between base-master.apk playstore (data/runs/fedora40-manual/apks-from-device/base-master.apk) and fedora41 (data/runs/fedora41-scripted-1/apks-i-built/base-master.apk)
4580
==============================
./diffuse check between base-master.apk playstore (data/runs/fedora40-manual/apks-from-device/base-master.apk) and ubuntu22_dfs_sort_reverse (data/runs/ubuntu22_dfs_sort_reverse-scripted/apks-i-built/base-master.apk)
8091
==============================
./diffuse check between base-master.apk playstore (data/runs/fedora40-manual/apks-from-device/base-master.apk) and ubuntu22_dfs_sort (data/runs/ubuntu22_dfs_sort-scripted/apks-i-built/base-master.apk)
6765
==============================
./diffuse check between base-master.apk playstore (data/runs/fedora40-manual/apks-from-device/base-master.apk) and ubuntu22 (data/runs/ubuntu22-scripted-1/apks-i-built/base-master.apk)
4488
==============================
./diffuse check between base-master.apk fedora40 (data/runs/fedora40-manual/apks-i-built/base-master.apk) and ubuntu22_dfs_sort_reverse (data/runs/ubuntu22_dfs_sort_reverse-scripted/apks-i-built/base-master.apk)
7045
==============================
./diffuse check between base-master.apk fedora40 (data/runs/fedora40-manual/apks-i-built/base-master.apk) and ubuntu22_dfs_sort (data/runs/ubuntu22_dfs_sort-scripted/apks-i-built/base-master.apk)
5689
==============================
./diffuse check between base-master.apk fedora40 (data/runs/fedora40-manual/apks-i-built/base-master.apk) and ubuntu22 (data/runs/ubuntu22-scripted-1/apks-i-built/base-master.apk)
3227
==============================
./diffuse check between base-master.apk fedora41 (data/runs/fedora41-scripted-1/apks-i-built/base-master.apk) and ubuntu22_dfs_sort_reverse (data/runs/ubuntu22_dfs_sort_reverse-scripted/apks-i-built/base-master.apk)
6385
==============================
./diffuse check between base-master.apk fedora41 (data/runs/fedora41-scripted-1/apks-i-built/base-master.apk) and ubuntu22_dfs_sort (data/runs/ubuntu22_dfs_sort-scripted/apks-i-built/base-master.apk)
5032
==============================
./diffuse check between base-master.apk fedora41 (data/runs/fedora41-scripted-1/apks-i-built/base-master.apk) and ubuntu22 (data/runs/ubuntu22-scripted-1/apks-i-built/base-master.apk)
2436
==============================
./diffuse check between base-master.apk ubuntu22_dfs_sort_reverse (data/runs/ubuntu22_dfs_sort_reverse-scripted/apks-i-built/base-master.apk) and ubuntu22_dfs_sort (data/runs/ubuntu22_dfs_sort-scripted/apks-i-built/base-master.apk)
3997
==============================
./diffuse check between base-master.apk ubuntu22_dfs_sort_reverse (data/runs/ubuntu22_dfs_sort_reverse-scripted/apks-i-built/base-master.apk) and ubuntu22 (data/runs/ubuntu22-scripted-1/apks-i-built/base-master.apk)
6325
==============================
./diffuse check between base-master.apk ubuntu22_dfs_sort (data/runs/ubuntu22_dfs_sort-scripted/apks-i-built/base-master.apk) and ubuntu22 (data/runs/ubuntu22-scripted-1/apks-i-built/base-master.apk)
5032
==============================
./diffuse check between base-xxhdpi.apk fedora40_dfs_sort_reverse (data/runs/fedora40_dfs_sort_reverse-scripted/apks-i-built/base-xxhdpi.apk) and playstore (data/runs/fedora40-manual/apks-from-device/base-xxhdpi.apk)
3599
==============================
./diffuse check between base-xxhdpi.apk playstore (data/runs/fedora40-manual/apks-from-device/base-xxhdpi.apk) and fedora40 (data/runs/fedora40-manual/apks-i-built/base-xxhdpi.apk)
3646

In [47]:
# !LOGURU_LEVEL="INFO" diffoscope --html diffoscope.html data/runs/fedora40-manual/apks-i-built/base-arm64_v8a.apk data/runs/fedora40-manual/apks-from-device/base-arm64_v8a.apk > /dev/null

In [48]:
from bs4 import BeautifulSoup


def clean_diffoscope_report(infile, outfile):
    # Define the ignore list (this could be keywords, specific file names, etc.)
    ignore_list = [
        "APK Signing Block",
        "zipinfo",
        "apksigner",
        # Add more ignore patterns here as needed
    ]
    ignore_list.extend(ApkDiff.IGNORE_FILES)

    # Function to check if the section should be ignored
    def should_ignore(section):
        text = section.text.lower()
        # print(text)
        # print("++++++++++++++++++++++++++++++++++++++++++++")
        for pattern in ignore_list:
            if pattern.lower() in text:
                print(f"{pattern} in text!")
                return True
        return False

    # Load the HTML file
    with open(infile, "r", encoding="utf-8") as file:
        soup = BeautifulSoup(file, "lxml")

    # Find all sections with the class 'difference' (or any other class you're interested in)
    parent_difference_div = soup.body.find("div", class_="difference")

    # If the parent div exists, proceed to find its children with class 'difference'
    if parent_difference_div:
        # Find all child divs with class 'difference' within this parent div
        difference_sections = parent_difference_div.find_all("div", class_="difference")

        # Iterate over all the 'difference' sections
        for section in difference_sections:
            if should_ignore(section):
                section.decompose()  # Remove the section from the tree

    # Save the modified HTML back to a file
    with open(outfile, "w", encoding="utf-8") as file:
        file.write(str(soup))
    print(f"Report updated and saved as '{outfile}'.")

In [51]:
# clean_diffoscope_report("diffoscope.html", "sanitized.html")

In [52]:
# Monkey-patching code directly in the notebook
# import diffoscope

# if androguard.version.startswith("4"):
#     from androguard.code import apk
# else:
#     from androguard.core.bytecodes import apk

In [53]:
diffoscope_results_dir = pathlib.Path("intermediates/diffoscope-results")
diffoscope_results_dir.mkdir(parents=True, exist_ok=True)

for index, row in mismatched.iterrows():
    print("==============================")
    print(
        f"./diffoscope check between {row['filename']} {row['apk1_origin']} ({row['apk1_filepath']}) and {row['apk2_origin']} ({row['apk2_filepath']})"
    )
    name = f"diffoscope_{row['filename']}__{row['apk1_origin']}_vs_{row['apk2_origin']}"
    orig_name = f"{name}.orig.html"
    name += ".html"

    !LOGURU_LEVEL="WARNING" diffoscope --html {str(diffoscope_results_dir / orig_name)} {row['apk1_filepath']} {row['apk2_filepath']}  >/dev/null
    print("Ran diffoscope. Now filtering...")
    clean_diffoscope_report(
        str(diffoscope_results_dir / orig_name), str(diffoscope_results_dir / name)
    )
    !rm -rf /tmp/diffoscope_* # tidy up
print("> Wrote all diffoscope results.")

==============================
./diffoscope check between base-arm64_v8a.apk fedora40_dfs_sort_reverse (data/runs/fedora40_dfs_sort_reverse-scripted/apks-i-built/base-arm64_v8a.apk) and playstore (data/runs/fedora40-manual/apks-from-device/base-arm64_v8a.apk)
Ran diffoscope. Now filtering...
APK Signing Block in text!
apksigner in text!
zipinfo in text!
stamp-cert-sha256 in text!
Report updated and saved as 'intermediates/diffoscope-results/diffoscope_base-arm64_v8a.apk__fedora40_dfs_sort_reverse_vs_playstore.html'.
==============================
./diffoscope check between base-arm64_v8a.apk playstore (data/runs/fedora40-manual/apks-from-device/base-arm64_v8a.apk) and fedora40 (data/runs/fedora40-manual/apks-i-built/base-arm64_v8a.apk)
Ran diffoscope. Now filtering...
APK Signing Block in text!
apksigner in text!
zipinfo in text!
stamp-cert-sha256 in text!
META-INF/MANIFEST.MF in text!
META-INF/BNDLTOOL.RSA in text!
META-INF/BNDLTOOL.SF in text!
Report updated and saved as 'intermediates/diffoscope-results/diffoscope_base-arm64_v8a.apk__playstore_vs_fedora40.html'.
==============================
./diffoscope check between base-arm64_v8a.apk playstore (data/runs/fedora40-manual/apks-from-device/base-arm64_v8a.apk) and fedora41 (data/runs/fedora41-scripted-1/apks-i-built/base-arm64_v8a.apk)
Ran diffoscope. Now filtering...
APK Signing Block in text!
apksigner in text!
zipinfo in text!
stamp-cert-sha256 in text!
Report updated and saved as 'intermediates/diffoscope-results/diffoscope_base-arm64_v8a.apk__playstore_vs_fedora41.html'.
==============================
./diffoscope check between base-master.apk fedora40_dfs_sort_reverse (data/runs/fedora40_dfs_sort_reverse-scripted/apks-i-built/base-master.apk) and fedora40_dfs_sort (data/runs/fedora40_dfs_sort-scripted/apks-i-built/base-master.apk)
Ran diffoscope. Now filtering...
zipinfo in text!
zipinfo in text!
zipinfo in text!
zipinfo in text!
zipinfo in text!
Report updated and saved as 'intermediates/diffoscope-results/diffoscope_base-master.apk__fedora40_dfs_sort_reverse_vs_fedora40_dfs_sort.html'.
==============================
./diffoscope check between base-master.apk fedora40_dfs_sort_reverse (data/runs/fedora40_dfs_sort_reverse-scripted/apks-i-built/base-master.apk) and playstore (data/runs/fedora40-manual/apks-from-device/base-master.apk)
Ran diffoscope. Now filtering...
APK Signing Block in text!
apksigner in text!
zipinfo in text!
stamp-cert-sha256 in text!
zipinfo in text!
zipinfo in text!
zipinfo in text!
zipinfo in text!
Report updated and saved as 'intermediates/diffoscope-results/diffoscope_base-master.apk__fedora40_dfs_sort_reverse_vs_playstore.html'.
==============================
./diffoscope check between base-master.apk fedora40_dfs_sort_reverse (data/runs/fedora40_dfs_sort_reverse-scripted/apks-i-built/base-master.apk) and fedora40 (data/runs/fedora40-manual/apks-i-built/base-master.apk)
Ran diffoscope. Now filtering...
APK Signing Block in text!
apksigner in text!
zipinfo in text!
zipinfo in text!
zipinfo in text!
zipinfo in text!
zipinfo in text!
Report updated and saved as 'intermediates/diffoscope-results/diffoscope_base-master.apk__fedora40_dfs_sort_reverse_vs_fedora40.html'.
==============================
./diffoscope check between base-master.apk fedora40_dfs_sort_reverse (data/runs/fedora40_dfs_sort_reverse-scripted/apks-i-built/base-master.apk) and fedora41 (data/runs/fedora41-scripted-1/apks-i-built/base-master.apk)
Ran diffoscope. Now filtering...
zipinfo in text!
zipinfo in text!
zipinfo in text!
zipinfo in text!
zipinfo in text!
Report updated and saved as 'intermediates/diffoscope-results/diffoscope_base-master.apk__fedora40_dfs_sort_reverse_vs_fedora41.html'.
==============================
./diffoscope check between base-master.apk fedora40_dfs_sort_reverse (data/runs/fedora40_dfs_sort_reverse-scripted/apks-i-built/base-master.apk) and ubuntu22_dfs_sort_reverse (data/runs/ubuntu22_dfs_sort_reverse-scripted/apks-i-built/base-master.apk)
Ran diffoscope. Now filtering...
zipinfo in text!
Report updated and saved as 'intermediates/diffoscope-results/diffoscope_base-master.apk__fedora40_dfs_sort_reverse_vs_ubuntu22_dfs_sort_reverse.html'.
==============================
./diffoscope check between base-master.apk fedora40_dfs_sort_reverse (data/runs/fedora40_dfs_sort_reverse-scripted/apks-i-built/base-master.apk) and ubuntu22_dfs_sort (data/runs/ubuntu22_dfs_sort-scripted/apks-i-built/base-master.apk)
Ran diffoscope. Now filtering...
zipinfo in text!
zipinfo in text!
zipinfo in text!
zipinfo in text!
zipinfo in text!
Report updated and saved as 'intermediates/diffoscope-results/diffoscope_base-master.apk__fedora40_dfs_sort_reverse_vs_ubuntu22_dfs_sort.html'.
==============================
./diffoscope check between base-master.apk fedora40_dfs_sort_reverse (data/runs/fedora40_dfs_sort_reverse-scripted/apks-i-built/base-master.apk) and ubuntu22 (data/runs/ubuntu22-scripted-1/apks-i-built/base-master.apk)
Ran diffoscope. Now filtering...
zipinfo in text!
zipinfo in text!
zipinfo in text!
zipinfo in text!
zipinfo in text!
zipinfo in text!
Report updated and saved as 'intermediates/diffoscope-results/diffoscope_base-master.apk__fedora40_dfs_sort_reverse_vs_ubuntu22.html'.
==============================
./diffoscope check between base-master.apk fedora40_dfs_sort (data/runs/fedora40_dfs_sort-scripted/apks-i-built/base-master.apk) and playstore (data/runs/fedora40-manual/apks-from-device/base-master.apk)
Ran diffoscope. Now filtering...
APK Signing Block in text!
apksigner in text!
zipinfo in text!
stamp-cert-sha256 in text!
zipinfo in text!
zipinfo in text!
zipinfo in text!
zipinfo in text!
Report updated and saved as 'intermediates/diffoscope-results/diffoscope_base-master.apk__fedora40_dfs_sort_vs_playstore.html'.
==============================
./diffoscope check between base-master.apk fedora40_dfs_sort (data/runs/fedora40_dfs_sort-scripted/apks-i-built/base-master.apk) and fedora40 (data/runs/fedora40-manual/apks-i-built/base-master.apk)
Ran diffoscope. Now filtering...
APK Signing Block in text!
apksigner in text!
zipinfo in text!
zipinfo in text!
zipinfo in text!
zipinfo in text!
zipinfo in text!
zipinfo in text!
Report updated and saved as 'intermediates/diffoscope-results/diffoscope_base-master.apk__fedora40_dfs_sort_vs_fedora40.html'.
==============================
./diffoscope check between base-master.apk fedora40_dfs_sort (data/runs/fedora40_dfs_sort-scripted/apks-i-built/base-master.apk) and fedora41 (data/runs/fedora41-scripted-1/apks-i-built/base-master.apk)
Ran diffoscope. Now filtering...
zipinfo in text!
zipinfo in text!
zipinfo in text!
zipinfo in text!
zipinfo in text!
zipinfo in text!
Report updated and saved as 'intermediates/diffoscope-results/diffoscope_base-master.apk__fedora40_dfs_sort_vs_fedora41.html'.
==============================
./diffoscope check between base-master.apk fedora40_dfs_sort (data/runs/fedora40_dfs_sort-scripted/apks-i-built/base-master.apk) and ubuntu22_dfs_sort_reverse (data/runs/ubuntu22_dfs_sort_reverse-scripted/apks-i-built/base-master.apk)
Ran diffoscope. Now filtering...
zipinfo in text!
zipinfo in text!
zipinfo in text!
zipinfo in text!
zipinfo in text!
Report updated and saved as 'intermediates/diffoscope-results/diffoscope_base-master.apk__fedora40_dfs_sort_vs_ubuntu22_dfs_sort_reverse.html'.
==============================
./diffoscope check between base-master.apk fedora40_dfs_sort (data/runs/fedora40_dfs_sort-scripted/apks-i-built/base-master.apk) and ubuntu22_dfs_sort (data/runs/ubuntu22_dfs_sort-scripted/apks-i-built/base-master.apk)
Ran diffoscope. Now filtering...
zipinfo in text!
Report updated and saved as 'intermediates/diffoscope-results/diffoscope_base-master.apk__fedora40_dfs_sort_vs_ubuntu22_dfs_sort.html'.
==============================
./diffoscope check between base-master.apk fedora40_dfs_sort (data/runs/fedora40_dfs_sort-scripted/apks-i-built/base-master.apk) and ubuntu22 (data/runs/ubuntu22-scripted-1/apks-i-built/base-master.apk)
Ran diffoscope. Now filtering...
zipinfo in text!
zipinfo in text!
zipinfo in text!
zipinfo in text!
zipinfo in text!
zipinfo in text!
Report updated and saved as 'intermediates/diffoscope-results/diffoscope_base-master.apk__fedora40_dfs_sort_vs_ubuntu22.html'.
==============================
./diffoscope check between base-master.apk playstore (data/runs/fedora40-manual/apks-from-device/base-master.apk) and fedora40 (data/runs/fedora40-manual/apks-i-built/base-master.apk)
Ran diffoscope. Now filtering...
APK Signing Block in text!
apksigner in text!
zipinfo in text!
stamp-cert-sha256 in text!
zipinfo in text!
zipinfo in text!
zipinfo in text!
zipinfo in text!
zipinfo in text!
META-INF/MANIFEST.MF in text!
META-INF/BNDLTOOL.RSA in text!
META-INF/BNDLTOOL.SF in text!
Report updated and saved as 'intermediates/diffoscope-results/diffoscope_base-master.apk__playstore_vs_fedora40.html'.
==============================
./diffoscope check between base-master.apk playstore (data/runs/fedora40-manual/apks-from-device/base-master.apk) and fedora41 (data/runs/fedora41-scripted-1/apks-i-built/base-master.apk)
Ran diffoscope. Now filtering...
APK Signing Block in text!
apksigner in text!
zipinfo in text!
stamp-cert-sha256 in text!
zipinfo in text!
zipinfo in text!
zipinfo in text!
zipinfo in text!
zipinfo in text!
Report updated and saved as 'intermediates/diffoscope-results/diffoscope_base-master.apk__playstore_vs_fedora41.html'.
==============================
./diffoscope check between base-master.apk playstore (data/runs/fedora40-manual/apks-from-device/base-master.apk) and ubuntu22_dfs_sort_reverse (data/runs/ubuntu22_dfs_sort_reverse-scripted/apks-i-built/base-master.apk)
Ran diffoscope. Now filtering...
APK Signing Block in text!
apksigner in text!
zipinfo in text!
stamp-cert-sha256 in text!
zipinfo in text!
zipinfo in text!
zipinfo in text!
zipinfo in text!
Report updated and saved as 'intermediates/diffoscope-results/diffoscope_base-master.apk__playstore_vs_ubuntu22_dfs_sort_reverse.html'.
==============================
./diffoscope check between base-master.apk playstore (data/runs/fedora40-manual/apks-from-device/base-master.apk) and ubuntu22_dfs_sort (data/runs/ubuntu22_dfs_sort-scripted/apks-i-built/base-master.apk)
Ran diffoscope. Now filtering...
APK Signing Block in text!
apksigner in text!
zipinfo in text!
stamp-cert-sha256 in text!
zipinfo in text!
zipinfo in text!
zipinfo in text!
zipinfo in text!
Report updated and saved as 'intermediates/diffoscope-results/diffoscope_base-master.apk__playstore_vs_ubuntu22_dfs_sort.html'.
==============================
./diffoscope check between base-master.apk playstore (data/runs/fedora40-manual/apks-from-device/base-master.apk) and ubuntu22 (data/runs/ubuntu22-scripted-1/apks-i-built/base-master.apk)
Ran diffoscope. Now filtering...
APK Signing Block in text!
apksigner in text!
zipinfo in text!
stamp-cert-sha256 in text!
zipinfo in text!
zipinfo in text!
zipinfo in text!
zipinfo in text!
Report updated and saved as 'intermediates/diffoscope-results/diffoscope_base-master.apk__playstore_vs_ubuntu22.html'.
==============================
./diffoscope check between base-master.apk fedora40 (data/runs/fedora40-manual/apks-i-built/base-master.apk) and ubuntu22_dfs_sort_reverse (data/runs/ubuntu22_dfs_sort_reverse-scripted/apks-i-built/base-master.apk)
Ran diffoscope. Now filtering...
APK Signing Block in text!
apksigner in text!
zipinfo in text!
zipinfo in text!
zipinfo in text!
zipinfo in text!
zipinfo in text!
Report updated and saved as 'intermediates/diffoscope-results/diffoscope_base-master.apk__fedora40_vs_ubuntu22_dfs_sort_reverse.html'.
==============================
./diffoscope check between base-master.apk fedora40 (data/runs/fedora40-manual/apks-i-built/base-master.apk) and ubuntu22_dfs_sort (data/runs/ubuntu22_dfs_sort-scripted/apks-i-built/base-master.apk)
Ran diffoscope. Now filtering...
APK Signing Block in text!
apksigner in text!
zipinfo in text!
zipinfo in text!
zipinfo in text!
zipinfo in text!
zipinfo in text!
zipinfo in text!
Report updated and saved as 'intermediates/diffoscope-results/diffoscope_base-master.apk__fedora40_vs_ubuntu22_dfs_sort.html'.
==============================
./diffoscope check between base-master.apk fedora40 (data/runs/fedora40-manual/apks-i-built/base-master.apk) and ubuntu22 (data/runs/ubuntu22-scripted-1/apks-i-built/base-master.apk)
Ran diffoscope. Now filtering...
APK Signing Block in text!
apksigner in text!
zipinfo in text!
zipinfo in text!
zipinfo in text!
zipinfo in text!
zipinfo in text!
Report updated and saved as 'intermediates/diffoscope-results/diffoscope_base-master.apk__fedora40_vs_ubuntu22.html'.
==============================
./diffoscope check between base-master.apk fedora41 (data/runs/fedora41-scripted-1/apks-i-built/base-master.apk) and ubuntu22_dfs_sort_reverse (data/runs/ubuntu22_dfs_sort_reverse-scripted/apks-i-built/base-master.apk)
Ran diffoscope. Now filtering...
zipinfo in text!
zipinfo in text!
zipinfo in text!
zipinfo in text!
zipinfo in text!
Report updated and saved as 'intermediates/diffoscope-results/diffoscope_base-master.apk__fedora41_vs_ubuntu22_dfs_sort_reverse.html'.
==============================
./diffoscope check between base-master.apk fedora41 (data/runs/fedora41-scripted-1/apks-i-built/base-master.apk) and ubuntu22_dfs_sort (data/runs/ubuntu22_dfs_sort-scripted/apks-i-built/base-master.apk)
Ran diffoscope. Now filtering...
zipinfo in text!
zipinfo in text!
zipinfo in text!
zipinfo in text!
zipinfo in text!
zipinfo in text!
Report updated and saved as 'intermediates/diffoscope-results/diffoscope_base-master.apk__fedora41_vs_ubuntu22_dfs_sort.html'.
==============================
./diffoscope check between base-master.apk fedora41 (data/runs/fedora41-scripted-1/apks-i-built/base-master.apk) and ubuntu22 (data/runs/ubuntu22-scripted-1/apks-i-built/base-master.apk)
Ran diffoscope. Now filtering...
zipinfo in text!
zipinfo in text!
zipinfo in text!
zipinfo in text!
zipinfo in text!
Report updated and saved as 'intermediates/diffoscope-results/diffoscope_base-master.apk__fedora41_vs_ubuntu22.html'.
==============================
./diffoscope check between base-master.apk ubuntu22_dfs_sort_reverse (data/runs/ubuntu22_dfs_sort_reverse-scripted/apks-i-built/base-master.apk) and ubuntu22_dfs_sort (data/runs/ubuntu22_dfs_sort-scripted/apks-i-built/base-master.apk)
Ran diffoscope. Now filtering...
zipinfo in text!
zipinfo in text!
zipinfo in text!
zipinfo in text!
zipinfo in text!
Report updated and saved as 'intermediates/diffoscope-results/diffoscope_base-master.apk__ubuntu22_dfs_sort_reverse_vs_ubuntu22_dfs_sort.html'.
==============================
./diffoscope check between base-master.apk ubuntu22_dfs_sort_reverse (data/runs/ubuntu22_dfs_sort_reverse-scripted/apks-i-built/base-master.apk) and ubuntu22 (data/runs/ubuntu22-scripted-1/apks-i-built/base-master.apk)
Ran diffoscope. Now filtering...
zipinfo in text!
zipinfo in text!
zipinfo in text!
zipinfo in text!
zipinfo in text!
zipinfo in text!
Report updated and saved as 'intermediates/diffoscope-results/diffoscope_base-master.apk__ubuntu22_dfs_sort_reverse_vs_ubuntu22.html'.
==============================
./diffoscope check between base-master.apk ubuntu22_dfs_sort (data/runs/ubuntu22_dfs_sort-scripted/apks-i-built/base-master.apk) and ubuntu22 (data/runs/ubuntu22-scripted-1/apks-i-built/base-master.apk)
Ran diffoscope. Now filtering...
zipinfo in text!
zipinfo in text!
zipinfo in text!
zipinfo in text!
zipinfo in text!
zipinfo in text!
Report updated and saved as 'intermediates/diffoscope-results/diffoscope_base-master.apk__ubuntu22_dfs_sort_vs_ubuntu22.html'.
==============================
./diffoscope check between base-xxhdpi.apk fedora40_dfs_sort_reverse (data/runs/fedora40_dfs_sort_reverse-scripted/apks-i-built/base-xxhdpi.apk) and playstore (data/runs/fedora40-manual/apks-from-device/base-xxhdpi.apk)
Ran diffoscope. Now filtering...
APK Signing Block in text!
apksigner in text!
zipinfo in text!
stamp-cert-sha256 in text!
Report updated and saved as 'intermediates/diffoscope-results/diffoscope_base-xxhdpi.apk__fedora40_dfs_sort_reverse_vs_playstore.html'.
==============================
./diffoscope check between base-xxhdpi.apk playstore (data/runs/fedora40-manual/apks-from-device/base-xxhdpi.apk) and fedora40 (data/runs/fedora40-manual/apks-i-built/base-xxhdpi.apk)
Ran diffoscope. Now filtering...
APK Signing Block in text!
apksigner in text!
zipinfo in text!
stamp-cert-sha256 in text!
META-INF/MANIFEST.MF in text!
META-INF/BNDLTOOL.RSA in text!
META-INF/BNDLTOOL.SF in text!
Report updated and saved as 'intermediates/diffoscope-results/diffoscope_base-xxhdpi.apk__playstore_vs_fedora40.html'.
> Wrote all diffoscope results.

In [69]:
# compare resources
!aapt2 dump chunks data/runs/fedora40-scripted-1/apks-from-device/base-xxhdpi.apk > r1
!aapt2 dump chunks data/runs/fedora41-scripted-1/apks-i-built/base-xxhdpi.apk > r2
!echo "aa" > b
!diff -s r1 r2
!rm r1 r2
# !apkanalyzer apk compare --different-only data/runs/fedora40-scripted-1/apks-from-device/base-xxhdpi.apk data/runs/fedora41-scripted-1/apks-i-built/base-xxhdpi.apk

Files r1 and r2 are identical

In [71]:
!aapt2 dump resources data/runs/fedora40-scripted-1/apks-from-device/base-xxhdpi.apk > r1
!aapt2 dump resources data/runs/fedora41-scripted-1/apks-i-built/base-xxhdpi.apk > r2
!diff -s r1 r2
!rm r1 r2

Files r1 and r2 are identical

In [ ]:
# !apkanalyzer compare packages data/runs/fedora40-scripted-1/apks-from-device/base-xxhdpi.apk # data/runs/fedora41-scripted-1/apks-i-built/base-xxhdpi.apk

In [ ]:
# !apkanalyzer compare packages data/runs/fedora40-scripted-1/apks-from-device/base-xxhdpi.apk # data/runs/fedora41-scripted-1/apks-i-built/base-xxhdpi.apk

In [ ]:
# !apkanalyzer dex compare packages data/runs/fedora40-scripted-1/apks-from-device/base-xxhdpi.apk # data/runs/fedora41-scripted-1/apks-i-built/base-xxhdpi.apk

In [72]:
!ls intermediates/apkdiff-results/base-master.apk_playstore_vs_fedora40/first/classes2.dex

intermediates/apkdiff-results/base-master.apk_playstore_vs_fedora40/first/classes2.dex

In [45]:
!dex-diff data/runs/fedora40-scripted-1/apks-from-device/base-master.apk data/runs/fedora40-scripted-1/apks-i-built/base-master.apk

(node:545582) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
⚔️ dex-diff v0.1.2
🧠 Heap size: 16384 MB
🚀 Initialising...
➡️ Decompiling before APK... (this may take some time)
🙌 decompiling base-master.apk skipped as cache exist
✅ Decompiling before APK finished
➡️ Decompiling after APK... (this may take some time)
🙌 decompiling base-master.apk skipped as cache exist
✅ Decompiling after APK finished
✅ Decompile finished (1193ms)
🙌 skipping new report file generation as cache exist
✅ Report ready (1.60s) -> file:///home/adrian/Dev/Shenanigans/reproducible-stuff/dex-diff-result/6a2e31ff088ecd970fe82fa52464eb0b_0070f5b6ad9290c0fe97211f9d459fee_report.html

In [73]:
assert 1 == 4

AssertionError:

============

In [ ]:
!pip install dexparser

In [ ]:
from dexparser import DEXParser

with open(
    "intermediates/apkdiff-results/base-master.apk_playstore_vs_fedora40/first/classes2.dex",
    "rb",
) as fileobj:
    dex = DEXParser(fileobj=fileobj.read())

In [ ]:
# dexdiff is too verbose to be easily analyzed (comes from google)
# dex-diff produces nice looking reports -- but it relies on deprecated libs and emits a lot of code, making it unsuitable for a git repo (expect maybe in CI)

In [ ]:
dex.header

In [ ]:
# dex.get_classdef_data()
typeids = dex.get_typeids()
strings = dex.get_strings()
for class_def in dex.get_classdef_data():
    type_id = typeids[class_def["class_idx"]]
    class_name = strings[type_id]
    print(class_def)
    print(class_name)
    # print("Parent:", strings[1935])
    break

In [ ]:
for index, row in mismatched.iterrows():
    print("==============================")
    print(
        f"./dex-diff check between {row['filename']} {row['apk1_origin']} ({row['apk1_filepath']}) and {row['apk2_origin']} ({row['apk2_filepath']})"
    )
    name = f"dex-diff_{row['filename']}__{row['apk1_origin']}_vs_{row['apk2_origin']}"
    orig_name = f"{name}.orig.html"
    name += ".html"

    !dex-diff {row['apk1_filepath']} {row['apk2_filepath']}
# !mkdir -p dex-diff-result/{name}
# !mv dex-diff-result/*.html dex-diff-result/{name}
# clean_diffoscope_report(str(diffoscope_results_dir / orig_name), str(diffoscope_results_dir / name))
print("> Wrote all dex-diff results.")

In [ ]:
# dex_analysis = analyze_dex_files(['./apkdiff-results/base-master.apk_playstore_vs_fedora40/first/classes2.dex', './apkdiff-results/base-master.apk_playstore_vs_fedora40/second/classes2.dex'])

# Conclusions

Based on the analysis above, we can draw the following conclusions:

1. Build Reproducibility: [This will be filled based on actual results]
2. Size Consistency: [This will be filled based on actual results]
3. Environment Impact: [This will be filled based on actual results]

### Recommendations

Based on these findings, here are some recommendations for improving build reproducibility:

1. [Will be filled based on actual results]
2. [Will be filled based on actual results]
3. [Will be filled based on actual results]